stages:
  - start
  - tezos-master

datadog_pipeline_trace:
  image: datadog/ci:v2.44.0
  stage: start
  tags:
  - gcp
  dependencies: []
  allow_failure: true
  timeout: 60 minutes
  interruptible: false
  script:
  - CI_MERGE_REQUEST_IID=${CI_MERGE_REQUEST_IID:-none}
  - DATADOG_SITE=datadoghq.eu datadog-ci tag --level pipeline --tags pipeline_type:$PIPELINE_TYPE
    --tags mr_number:$CI_MERGE_REQUEST_IID

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml


container_scanning:
  stage: tezos-master
  tags:
  - gcp
  variables:
    CS_IMAGE: tezos/tezos:master
    SECURE_LOG_LEVEL: "debug"
