package:create_package:
  stage: publish_package_gitlab
  # Publish jobs are uninterruptible to avoid publishing partial results.
  interruptible: false
  dependencies:
    - build:static-x86_64-linux-binaries
    - build:static-arm64-linux-binaries
    - docker:merge_manifests
  script:
    - ${CI_PROJECT_DIR}/scripts/ci/create_gitlab_package.sh