---
default:
  interruptible: true
  tags:
    - gcp

stages:
  - lint
  - build
  - manifest
  - test

variables:
  HADOLINT_VERSION: 2.10.0 # TODO update to 2.12.0 (9 Nov 2022)
  BINFMT_VERSION: 6.2.0-26
  IMAGE_NAME: "ci-docker" # TODO should be ci/base after more integration work is done
  GCP_ARTIFACT_REGISTRY_IMAGE: "${GCP_REGISTRY}/${CI_PROJECT_PATH}/${IMAGE_NAME}"
  CONTAINER_NAME: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}"
  # Version of the docker to use, docker daemon and client must have the same
  DOCKER_VERSION: "24.0.7"
  # TODO check if variable below is used, remove it if it is not
  GCP_PROTECTED_ARTIFACT_REGISTRY_IMAGE: "${GCP_PROTECTED_REGISTRY}/${CI_PROJECT_PATH}/${IMAGE_NAME}"

hadolint:
  stage: lint
  image: "hadolint/hadolint:v${HADOLINT_VERSION}-debian"
  script:
    - hadolint ./images_base/ci-docker/Dockerfile
  allow_failure: true

docker-buildx:
  stage: build
  image: "${CI_REGISTRY}/tezos/docker-images/ci-docker:v1.9.0" # TODO update to 1.12.0
  services:
    - docker:${DOCKER_VERSION}-dind
  before_script:
    - ./scripts/ci/docker_wait_for_daemon.sh
    - ./scripts/ci/docker_check_version.sh ${DOCKER_VERSION}
  script:
    - ./images_base/ci-docker/scripts/build.sh

include:
  - template: Security/Container-Scanning.gitlab-ci.yml

container_scanning:
  stage: test
  services:
    - docker:${DOCKER_VERSION}-dind
  # DOCKER_IMAGE_TAG not available for use in CS_IMAGE
  # thus pointless to define [before_script] running [tag.sh]
  # before_script:
  #   - ./images_base/ci-docker/scripts/tag.sh
  #   # - ./scripts/docker_registry_auth.sh
  variables:
    GIT_STRATEGY: fetch
    # DOCKERFILE_PATH: "Dockerfile"
    # DOCKER_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    # CS_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}
    # CS_IMAGE: "${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_TAG}"
    # DOCKER_IMAGE_TAG not available
    # CS_IMAGE: ${GCP_ARTIFACT_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}
    # TODO revisit CS_IMAGE name when integration is more advanced
    CS_IMAGE: ${GCP_ARTIFACT_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME}
    SECURE_LOG_LEVEL: "debug"
  artifacts:
    paths:
    - gl-container-scanning-report.json
    expire_in: 1 week
