(* Generated by ocaml-rs *)

open! Bigarray

(* file: lib.rs *)

type repo
type state
type mut_state
type id
type status = Evaluating | Waiting_for_input | Waiting_for_reveal
type input = Inbox_message of {inbox_level: int32; message_counter: int64; payload: bytes} | Reveal of bytes
type input_request = No_input_required | Initial | First_after of {level: int32; counter: int64} | Needs_reveal of bytes
type output_info = {message_index : int64; outbox_level : int32}
type output = {info : output_info; encoded_message : bytes}
type output_proof
type proof
external octez_riscv_from_imm: state -> mut_state = "octez_riscv_from_imm"
external octez_riscv_to_imm: mut_state -> state = "octez_riscv_to_imm"
external octez_riscv_id_unsafe_of_raw_bytes: bytes -> id = "octez_riscv_id_unsafe_of_raw_bytes"
external octez_riscv_storage_id_to_raw_bytes: id -> bytes = "octez_riscv_storage_id_to_raw_bytes"
external octez_riscv_storage_id_equal: id -> id -> bool = "octez_riscv_storage_id_equal"
external octez_riscv_storage_state_equal: state -> state -> bool = "octez_riscv_storage_state_equal"
external octez_riscv_storage_mut_state_equal: mut_state -> mut_state -> bool = "octez_riscv_storage_mut_state_equal"
external octez_riscv_storage_state_empty: unit -> state = "octez_riscv_storage_state_empty"
external octez_riscv_storage_mut_state_empty: unit -> mut_state = "octez_riscv_storage_mut_state_empty"
external octez_riscv_storage_load: string -> repo = "octez_riscv_storage_load"
external octez_riscv_storage_close: repo -> unit = "octez_riscv_storage_close"
external octez_riscv_storage_commit: repo -> state -> id = "octez_riscv_storage_commit"
external octez_riscv_storage_checkout: repo -> id -> state option = "octez_riscv_storage_checkout"
external octez_riscv_get_status: state -> status = "octez_riscv_get_status"
external octez_riscv_mut_get_status: mut_state -> status = "octez_riscv_mut_get_status"
external octez_riscv_string_of_status: status -> string = "octez_riscv_string_of_status"
external octez_riscv_compute_step: state -> state = "octez_riscv_compute_step"
external octez_riscv_compute_step_with_debug: state -> (bytes -> unit) -> state = "octez_riscv_compute_step_with_debug"
external octez_riscv_compute_step_many: int64 -> state -> (state * int64) = "octez_riscv_compute_step_many"
external octez_riscv_mut_compute_step_many: int64 -> mut_state -> int64 = "octez_riscv_mut_compute_step_many"
external octez_riscv_compute_step_many_with_debug: int64 -> state -> (bytes -> unit) -> (state * int64) = "octez_riscv_compute_step_many_with_debug"
external octez_riscv_mut_compute_step_many_with_debug: int64 -> mut_state -> (bytes -> unit) -> int64 = "octez_riscv_mut_compute_step_many_with_debug"
external octez_riscv_get_tick: state -> int64 = "octez_riscv_get_tick"
external octez_riscv_mut_get_tick: mut_state -> int64 = "octez_riscv_mut_get_tick"
external octez_riscv_get_level: state -> int32 option = "octez_riscv_get_level"
external octez_riscv_mut_get_level: mut_state -> int32 option = "octez_riscv_mut_get_level"
external octez_riscv_install_boot_sector: state -> bytes -> state = "octez_riscv_install_boot_sector"
external octez_riscv_mut_install_boot_sector: mut_state -> bytes -> unit = "octez_riscv_mut_install_boot_sector"
external octez_riscv_state_hash: state -> bytes = "octez_riscv_state_hash"
external octez_riscv_mut_state_hash: mut_state -> bytes = "octez_riscv_mut_state_hash"
external octez_riscv_set_input: state -> input -> state = "octez_riscv_set_input"
external octez_riscv_mut_set_input: mut_state -> input -> unit = "octez_riscv_mut_set_input"
external octez_riscv_get_message_counter: state -> int64 = "octez_riscv_get_message_counter"
external octez_riscv_mut_get_message_counter: mut_state -> int64 = "octez_riscv_mut_get_message_counter"
external octez_riscv_storage_export_snapshot: repo -> id -> string -> (unit, [`Msg of string]) result = "octez_riscv_storage_export_snapshot"
external octez_riscv_proof_start_state: proof -> bytes = "octez_riscv_proof_start_state"
external octez_riscv_proof_stop_state: proof -> bytes = "octez_riscv_proof_stop_state"
external octez_riscv_produce_proof: input option -> state -> proof option = "octez_riscv_produce_proof"
external octez_riscv_verify_proof: input option -> proof -> input_request option = "octez_riscv_verify_proof"
external octez_riscv_serialise_proof: proof -> bytes = "octez_riscv_serialise_proof"
external octez_riscv_deserialise_proof: bytes -> (proof, string) Result.t = "octez_riscv_deserialise_proof"
external octez_riscv_output_info_of_output_proof: output_proof -> output_info = "octez_riscv_output_info_of_output_proof"
external octez_riscv_state_of_output_proof: output_proof -> bytes = "octez_riscv_state_of_output_proof"
external octez_riscv_verify_output_proof: output_proof -> output option = "octez_riscv_verify_output_proof"
external octez_riscv_serialise_output_proof: output_proof -> bytes = "octez_riscv_serialise_output_proof"
external octez_riscv_deserialise_output_proof: bytes -> (output_proof, string) result = "octez_riscv_deserialise_output_proof"
external octez_riscv_get_reveal_request: state -> bytes = "octez_riscv_get_reveal_request"
external octez_riscv_mut_get_reveal_request: mut_state -> bytes = "octez_riscv_mut_get_reveal_request"
external octez_riscv_insert_failure: state -> state = "octez_riscv_insert_failure"
external octez_riscv_mut_insert_failure: mut_state -> unit = "octez_riscv_mut_insert_failure"
external octez_riscv_test_status: status -> status = "octez_riscv_test_status"
external octez_riscv_test_input: input -> input = "octez_riscv_test_input"
external octez_riscv_test_input_request: input_request -> input_request = "octez_riscv_test_input_request"
external octez_riscv_test_output_info: output_info -> output_info = "octez_riscv_test_output_info"
external octez_riscv_test_output: output -> output = "octez_riscv_test_output"
