(* Do not edit this file manually.
   This file was automatically generated from benchmark models
   If you wish to update a function in this file,
   a. update the corresponding model, or
   b. move the function to another module and edit it there. *)

[@@@warning "-33"]

module S = Saturation_repr
open S.Syntax

(* model dal/Dal_publish_slot_header *)
(* max 10 1160000. *)
let cost_Dal_publish_slot_header = S.safe_int 1160000
