(* Do not edit this file manually.
   This file was automatically generated from benchmark models
   If you wish to update a function in this file,
   a. update the corresponding model, or
   b. move the function to another module and edit it there. *)

[@@@warning "-33"]

module S = Saturation_repr
open S.Syntax

(* model tickets/COLLECT_TICKETS_STEP *)
(* fun size -> 0. + (80. * size) *)
let cost_COLLECT_TICKETS_STEP size =
  let size = S.safe_int size in
  let v0 = size in
  v0 * S.safe_int 80

(* model tickets/COMPARE_CONTRACT *)
(* 10. *)
let cost_COMPARE_CONTRACT = S.safe_int 10

(* model tickets/COMPARE_TICKET_HASH *)
(* 10. *)
let cost_COMPARE_TICKET_HASH = S.safe_int 10

(* model tickets/TYPE_HAS_TICKETS *)
(* fun size -> 10. + (6. * size) *)
let cost_TYPE_HAS_TICKETS size =
  let v0 = size in
  S.safe_int 10 + (v0 * S.safe_int 6)
