lib: [

  "src/META"

  "src/resto.mli"
  "src/resto.ml"
  "_obuild/ocplib-resto/resto.cmi"
  "_obuild/ocplib-resto/resto.cmx"
  "?_obuild/ocplib-resto/resto.cmti"
  "?_obuild/ocplib-resto/resto.cmt"

  "src/ezResto.mli"
  "src/ezResto.ml"
  "_obuild/ocplib-resto/ezResto.cmi"
  "_obuild/ocplib-resto/ezResto.cmx"
  "?_obuild/ocplib-resto/ezResto.cmti"
  "?_obuild/ocplib-resto/ezResto.cmt"

  "_obuild/ocplib-resto/ocplib-resto.cma"
  "?_obuild/ocplib-resto/ocplib-resto.cmxa"
  "?_obuild/ocplib-resto/ocplib-resto.cmxs"
  "?_obuild/ocplib-resto/ocplib-resto.a"

  "src/restoDirectory.mli" { "directory/restoDirectory.mli" }
  "src/restoDirectory.ml" { "directory/restoDirectory.ml" }
  "_obuild/ocplib-resto-directory/restoDirectory.cmi"
     { "directory/restoDirectory.cmi" }
  "_obuild/ocplib-resto-directory/restoDirectory.cmx"
     { "directory/restoDirectory.cmx" }
  "?_obuild/ocplib-resto-directory/restoDirectory.cmti"
     { "directory/restoDirectory.cmti" }
  "?_obuild/ocplib-resto-directory/restoDirectory.cmt"
     { "directory/restoDirectory.cmt" }

  "src/ezRestoDirectory.mli"
     { "directory/ezRestoDirectory.mli" }
  "src/ezRestoDirectory.ml"
     { "directory/ezRestoDirectory.ml" }
  "_obuild/ocplib-resto-directory/ezRestoDirectory.cmi"
     { "directory/ezRestoDirectory.cmi" }
  "_obuild/ocplib-resto-directory/ezRestoDirectory.cmx"
     { "directory/ezRestoDirectory.cmx" }
  "?_obuild/ocplib-resto-directory/ezRestoDirectory.cmti"
     { "directory/ezRestoDirectory.cmti" }
  "?_obuild/ocplib-resto-directory/ezRestoDirectory.cmt"
     { "directory/ezRestoDirectory.cmt" }

  "_obuild/ocplib-resto-directory/ocplib-resto-directory.cma"
     { "directory/ocplib-resto-directory.cma" }
  "?_obuild/ocplib-resto-directory/ocplib-resto-directory.cmxa"
     { "directory/ocplib-resto-directory.cmxa" }
  "?_obuild/ocplib-resto-directory/ocplib-resto-directory.cmxs"
     { "directory/ocplib-resto-directory.cmxs" }
  "?_obuild/ocplib-resto-directory/ocplib-resto-directory.a"
     { "directory/ocplib-resto-directory.a" }

]