(*****************************************************************************)
(*                                                                           *)
(* SPDX-License-Identifier: MIT                                              *)
(* Copyright (c) 2025 Functori <contact@functori.com>                        *)
(*                                                                           *)
(*****************************************************************************)

(* Generate a migrations module from SQL and OCaml migration files.

   Usage: gen_migrations <dir> <output>

   Scans <dir> for:
   - N_name.sql   -> embeds SQL content, wraps in [Sqlite.Migration.make_sql]
   - mN_name.ml   -> references module [MN_name] for OCaml migration steps

   Outputs a single .ml file with [val all : Sqlite.Migration.t list]. *)

type entry =
  | Sql of {num : int; name : string; filename : string}
  | Ocaml_mod of {num : int; module_name : string}

(* Matches "m?N+_name.ext" — optional leading 'm', one or more digits, '_',
   name, '.', extension. *)
let filename_re = Re.Pcre.re {|^(m?)(\d+)_(.+)\.(sql|ml)$|} |> Re.compile

let parse_filename filename =
  match Re.exec_opt filename_re filename with
  | None -> None
  | Some g -> (
      let prefix = Re.Group.get g 1 in
      let num = int_of_string (Re.Group.get g 2) in
      let name = Re.Group.get g 3 in
      let ext = Re.Group.get g 4 in
      match (prefix, ext) with
      | "", "sql" -> Some (Sql {num; name; filename})
      | "m", "ml" ->
          let base = Filename.remove_extension filename in
          let module_name = String.capitalize_ascii base in
          Some (Ocaml_mod {num; module_name})
      | _ -> None)

let entry_num = function Sql {num; _} -> num | Ocaml_mod {num; _} -> num

let entry_filename = function
  | Sql {filename; _} -> filename
  | Ocaml_mod {module_name; _} -> module_name

let validate_numbering entries =
  let rec check = function
    | [] -> ()
    | [_] -> ()
    | a :: (b :: _ as rest) ->
        let na = entry_num a and nb = entry_num b in
        if na = nb then
          Format.ksprintf
            failwith
            "Duplicate migration number %d (%s and %s)"
            na
            (entry_filename a)
            (entry_filename b) ;
        if nb > na + 1 then
          Format.ksprintf
            failwith
            "Gap in migration numbering: %d is followed by %d"
            na
            nb ;
        check rest
  in
  (match entries with
  | first :: _ when entry_num first <> 0 ->
      Format.ksprintf
        failwith
        "First migration must be numbered 000, got %d"
        (entry_num first)
  | _ -> ()) ;
  check entries

let read_file path =
  let ic = open_in path in
  let n = in_channel_length ic in
  let s = Bytes.create n in
  really_input ic s 0 n ;
  close_in ic ;
  Bytes.to_string s

let () =
  if Array.length Sys.argv < 3 then (
    Printf.eprintf "Usage: gen_migrations <dir> <output>\n" ;
    exit 1) ;
  let dir = Sys.argv.(1) in
  let output = Sys.argv.(2) in
  let entries =
    Sys.readdir dir |> Array.to_list
    |> List.filter_map parse_filename
    |> List.sort (fun a b -> compare (entry_num a) (entry_num b))
  in
  validate_numbering entries ;
  let oc = open_out output in
  Printf.fprintf oc "(* Generated by gen_migrations -- do not edit. *)\n\n" ;
  Printf.fprintf oc "let all : Sqlite.Migration.t list =\n" ;
  Printf.fprintf oc "  [\n" ;
  List.iter
    (fun entry ->
      match entry with
      | Sql {name; filename; _} ->
          let content = read_file (Filename.concat dir filename) in
          Printf.fprintf oc "    Sqlite.Migration.make_sql ~name:%S\n" name ;
          Printf.fprintf oc "      {sql|%s|sql};\n" content
      | Ocaml_mod {module_name; _} ->
          Printf.fprintf
            oc
            "    {\n\
            \      Sqlite.Migration.name = %s.name;\n\
            \      steps = %s.up;\n\
            \    };\n"
            module_name
            module_name)
    entries ;
  Printf.fprintf oc "  ]\n" ;
  close_out oc
