[package]
name = "jstz"
version = "0.0.0"
edition = "2021"

[dependencies]
bincode.workspace = true
hex.workspace = true
jstz_kernel.workspace = true
serde.workspace = true
serde_json.workspace = true
tezos_crypto_rs.workspace = true
tezos-smart-rollup.workspace = true

[features]
default = []
static-inbox = []
