{
 "title": "Octez DAL Node Dashboard",
 "tags": [
  "tezos",
  "octez",
  "dal"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": "label_values(dal_node_new_layer1_head,app)"
   },
   {
    "name": "slot_index",
    "label": "Slot index",
    "query": "label_values(dal_gs_count_peers_per_topic, slot_index)"
   },
   {
    "name": "pkh",
    "label": "Pkh",
    "query": "label_values(dal_gs_count_peers_per_topic, pkh)"
   },
   {
    "name": "peer",
    "label": "Peer",
    "query": "label_values(dal_gs_scores_of_peers, peer)"
   }
  ]
 },
 "panels": [
  { "title": "DAL node's core stats", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Layer 1 heads & finalized blocks seen by the DAL node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_new_layer1_head{app=\"$node_instance\"}",
     "legendFormat": "Seen L1 heads"
    },
    {
     "expr": "dal_node_layer1_block_finalized{app=\"$node_instance\"}",
     "legendFormat": "Finalized L1 blocks"
    }
   ]
  },
  {
   "title": "Rounds of layer 1 heads & finalized blocks seen by the DAL node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_new_layer1_head_round{app=\"$node_instance\"}",
     "legendFormat": "Seen L1 heads' rounds"
    },
    {
     "expr": "dal_node_layer1_block_finalized_round{app=\"$node_instance\"}",
     "legendFormat": "Finalized L1 blocks' rounds"
    }
   ]
  },
  {
   "title": "The number of shards stored per second (over 1min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_node_number_of_stored_shards{app=\"$node_instance\"}[1m])",
     "legendFormat": "Stored shards"
    }
   ]
  },
  {
   "title": "Number of slots waiting for attesatation and of attested slots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dal_node_slots_waiting_for_attestaion{app=\"$node_instance\", slot_index=~\"$slot_index\"})",
     "legendFormat": "Number of slots waiting for attestation"
    },
    {
     "expr": "sum(dal_node_slots_attested{app=\"$node_instance\", slot_index=~\"$slot_index\"})",
     "legendFormat": "Number of attested slots"
    }
   ]
  },
  {
   "title": "Indexes of slots waiting for attestation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_slots_waiting_for_attestaion{app=\"$node_instance\", slot_index=~\"$slot_index\"}",
     "legendFormat": "Slot index: {{ slot_index }}"
    }
   ]
  },
  {
   "title": "Indexes of attested slots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_slots_attested{app=\"$node_instance\", slot_index=~\"$slot_index\"}",
     "legendFormat": "Slot index: {{ slot_index }}"
    }
   ]
  },
  { "title": "Gossipsub worker's stats", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Score of the peers connected to this node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_scores_of_peers{app=\"$node_instance\", peer=\"$peer\"}",
     "legendFormat": "{{ peer }}"
    }
   ]
  },
  {
   "title": "Number of peers in the mesh for each subscribed topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_count_peers_per_topic{app=\"$node_instance\", slot_index=~\"$slot_index\", pkh=\"$pkh\"}",
     "legendFormat": "Topic: {{ slot_index }}, {{ pkh }}"
    }
   ]
  },
  {
   "title": "The number of topics the node is subscribed to",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_count_topics{app=\"$node_instance\"}",
     "legendFormat": "Node's topics"
    }
   ]
  },
  {
   "title": "The number of (bootstrap) connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_count_connections{app=\"$node_instance\"}",
     "legendFormat": "All connections"
    },
    {
     "expr": "dal_gs_count_bootstrap_connections{app=\"$node_instance\"}",
     "legendFormat": "Bootstrap connections"
    }
   ]
  },
  {
   "title": "The size of different worker streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_input_events_stream_length{app=\"$node_instance\"}",
     "legendFormat": "Input stream"
    },
    {
     "expr": "dal_gs_p2p_output_stream_length{app=\"$node_instance\"}",
     "legendFormat": "P2P output stream"
    },
    {
     "expr": "dal_gs_app_output_stream_length{app=\"$node_instance\"}",
     "legendFormat": "Application output stream"
    }
   ]
  },
  {
   "title": "Average sent & received app messages per second (over 1min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_gs_count_received_valid_messages{app=\"$node_instance\"}[1m])",
     "legendFormat": "Received & valid"
    },
    {
     "expr": "deriv(dal_gs_count_received_invalid_messages{app=\"$node_instance\"}[1m])",
     "legendFormat": "Received & invalid"
    },
    {
     "expr": "deriv(dal_gs_count_received_unknown_validity_messages{app=\"$node_instance\"}[1m])",
     "legendFormat": "Received & unchecked validity"
    },
    {
     "expr": "deriv(dal_gs_count_sent_messages{app=\"$node_instance\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average sent control & metadata messages per second (over 1min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_gs_count_sent_grafts{app=\"$node_instance\"}[1m])",
     "legendFormat": "Graft"
    },
    {
     "expr": "deriv(dal_gs_count_sent_prunes{app=\"$node_instance\"}[1m])",
     "legendFormat": "Prune"
    },
    {
     "expr": "deriv(dal_gs_count_sent_ihaves{app=\"$node_instance\"}[1m])",
     "legendFormat": "IHave"
    },
    {
     "expr": "deriv(dal_gs_count_sent_iwants{app=\"$node_instance\"}[1m])",
     "legendFormat": "IWant"
    }
   ]
  },
  {
   "title": "Average received control & metadata messages per second (over 1min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_gs_count_received_grafts{app=\"$node_instance\"}[1m])",
     "legendFormat": "Graft"
    },
    {
     "expr": "deriv(dal_gs_count_received_prunes{app=\"$node_instance\"}[1m])",
     "legendFormat": "Prune"
    },
    {
     "expr": "deriv(dal_gs_count_received_ihaves{app=\"$node_instance\"}[1m])",
     "legendFormat": "IHave"
    },
    {
     "expr": "deriv(dal_gs_count_received_iwants{app=\"$node_instance\"}[1m])",
     "legendFormat": "IWant"
    }
   ]
  },
  { "title": "P2P stats", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Average data exchange per second (over 1min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(octez_p2p_io_scheduler_total_recv{app=\"$node_instance\"}[1m]) / 1000",
     "legendFormat": "Received data (KB)"
    },
    {
     "expr": "deriv(octez_p2p_io_scheduler_total_sent{app=\"$node_instance\"}[1m]) / 1000",
     "legendFormat": "Sent data (KB)"
    }
   ]
  },
  {
   "title": "P2P total connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_connections_outgoing{app=\"$node_instance\"}",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "octez_p2p_connections_incoming{app=\"$node_instance\"}",
     "legendFormat": "Incoming connections"
    }
   ]
  },
  {
   "title": "P2P peers connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_peers_disconnected{app=\"$node_instance\"}",
     "legendFormat": "Disconnected peers"
    },
    {
     "expr": "octez_p2p_peers_running{app=\"$node_instance\"}",
     "legendFormat": "Running peers"
    },
    {
     "expr": "octez_p2p_points_greylisted{app=\"$node_instance\"}",
     "legendFormat": "Waiting to reconnect"
    }
   ]
  },
  {
   "title": "P2P points connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_points_disconnected{app=\"$node_instance\"}",
     "legendFormat": "Disconnected points"
    },
    {
     "expr": "octez_p2p_points_running{app=\"$node_instance\"}",
     "legendFormat": "Running points"
    },
    {
     "expr": "octez_p2p_points_trusted{app=\"$node_instance\"}",
     "legendFormat": "Trusted points"
    }
   ]
  },
  { "title": "Amplification", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Total number of reconstructions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "dal_node_amplification_reconstructions_done_count{app=\"$node_instance\"}",
     "legendFormat": "Reconstructions done"
    },
    {
     "expr": "dal_node_amplification_reconstructions_aborted_count{app=\"$node_instance\"}",
     "legendFormat": "Reconstructions aborted"
    },
    {
     "expr": "dal_node_amplification_reconstructions_started_count{app=\"$node_instance\"}",
     "legendFormat": "Reconstructions started"
    }
   ]
  },
  {
   "title": "Average number of reconstructions per second (over 1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "rate(dal_node_amplification_reconstructions_done_count{app=\"$node_instance\"}[1m]) * 60",
     "legendFormat": "Reconstructions done"
    },
    {
     "expr": "rate(dal_node_amplification_reconstructions_aborted_count{app=\"$node_instance\"}[1m] ) * 60",
     "legendFormat": "Reconstructions aborted"
    },
    {
     "expr": "rate(dal_node_amplification_reconstructions_started_count{app=\"$node_instance\"}[1m]) * 60",
     "legendFormat": "Reconstructions started"
    }
   ]
  },
  {
   "title": "Amplification delays (histogram quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dal_node_amplification_start_reconstruction_duration_seconds_bucket{app=\"$node_instance\"}[$__rate_interval])) by  (le))",
     "legendFormat": "Delay from first shard received to start of amplification"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dal_node_amplification_abort_reconstruction_duration_seconds_bucket{app=\"$node_instance\"}[$__rate_interval])) by  (le))",
     "legendFormat": "Delay from first shard received to abortion of amplification"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dal_node_amplification_enough_shards_received_duration_seconds_bucket{app=\"$node_instance\"}[$__rate_interval])) by  (le))",
     "legendFormat": "Delay from first shard received to enough of shards received"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dal_node_amplification_all_shards_received_duration_seconds_bucket{app=\"$node_instance\"}[$__rate_interval])) by  (le))",
     "legendFormat": "Delay from first shard received to all shards received"
    }
   ]
  },
  {
   "title": "Amplification queue length (octez-dal-node main process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 140 },
   "targets": [
    {
     "expr": "dal_node_amplification_queue_length{app=\"$node_instance\"}",
     "legendFormat": "Number of reconstructions queued"
    }
   ]
  },
  {
   "title": "Reconstruction duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 140 },
   "targets": [
    {
     "expr": "rate(dal_node_amplification_complete_duration_seconds_sum{app=\"$node_instance\"}[$__rate_interval]) / rate(dal_node_amplification_complete_duration_seconds_count{app=\"$node_instance\"}[$__rate_interval])",
     "legendFormat": "Average amplification time (ipc, proof and publication)"
    }
   ]
  }
 ]
}