{
 "title": "Etherlink",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": {
     "query": "label_values(octez_evm_node_info,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{commit_hash}}"
    }
   ]
  },
  {
   "title": "Commit Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{commit_date}}"
    }
   ]
  },
  {
   "title": "Devmode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{devmode}}"
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RPC Calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(octez_evm_node_calls_count{app=\"$node_instance\"})",
     "legendFormat": "{{commit_hash}}"
    }
   ]
  },
  {
   "title": "RPC Average duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(octez_evm_node_calls_sum{app=\"$node_instance\"})/sum(octez_evm_node_calls_count{app=\"$node_instance\"})",
     "legendFormat": "{{commit_hash}}"
    }
   ]
  },
  {
   "title": "Head",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_head{app=\"$node_instance\"}",
     "legendFormat": "Node head"
    },
    {
     "expr": "octez_evm_node_confirmed_head{app=\"$node_instance\"}",
     "legendFormat": "Rollup node head"
    }
   ]
  },
  {
   "title": "Levels",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 2, "y": 3 },
   "targets": [
    {
     "expr": "octez_evm_node_confirmed_head{app=\"$node_instance\"}",
     "legendFormat": "Rollup-node's level"
    },
    {
     "expr": "octez_evm_node_head{app=\"$node_instance\"}",
     "legendFormat": "Node's level"
    }
   ]
  },
  {
   "title": "Average processing time",
   "type": "timeseries",
   "description": "The average is computed over 15 seconds.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "($A-$B)/($C-$D)", "type": "math" }
   ]
  },
  {
   "title": "Processing time distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_block_process_time_histogram_bucket{app=\"$node_instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transaction pool addresses count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_tx_pool{kind=\"number_of_addresses\", app=\"$node_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction pool transactions count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_evm_node_tx_pool{kind=\"number_of_transactions\", app=\"$node_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}