{
 "title": "Octez Rollup Node",
 "tags": [
  "tezos",
  "octez",
  "rollups"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": "label_values(octez_sc_rollup_node_node_info,app)"
   }
  ]
 },
 "panels": [
  { "title": "Version info", "type": "row" },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Git Commit Date",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{ commit_date }}"
    }
   ]
  },
  {
   "title": "Git Commit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(label_replace(octez_sc_rollup_node_node_info{app=\"$node_instance\"},\"commit_hash_short\" ,\"$1\",\"commit_hash\",\"^(.{8}).*$\"))",
     "legendFormat": "{{ commit_hash_short }}"
    }
   ]
  },
  { "title": "Generic information", "type": "row", "gridPos": { "h": 12, "w": 17, "x": 0, "y": 5 } },
  {
   "title": "Genesis Level",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{ genesis_level }}"
    }
   ]
  },
  {
   "title": "Pvm Kind",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{ pvm_kind }}"
    }
   ]
  },
  {
   "title": "Genesis Hash",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{ genesis_hash }}"
    }
   ]
  },
  {
   "title": "Rollup Address",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{app=\"$node_instance\"}",
     "legendFormat": "{{ rollup_address }}"
    }
   ]
  },
  { "title": "Inbox", "type": "row", "gridPos": { "h": 12, "w": 17, "x": 0, "y": 17 } },
  {
   "title": "Head Inbox Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_sc_rollup_node_head_inbox_level{app=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Genesis Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(octez_sc_rollup_node_head_inbox_internal_messages_number{app=\"$node_instance\"}[15m])+ rate(octez_sc_rollup_node_head_inbox_external_messages_number{app=\"$node_instance\"}[15m])"
    }
   ]
  },
  {
   "title": "Internal Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(octez_sc_rollup_node_head_inbox_internal_messages_number{app=\"$node_instance\"}[15m])"
    }
   ]
  },
  {
   "title": "External Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(octez_sc_rollup_node_head_inbox_internal_messages_number{app=\"$node_instance\"}[15m])"
    }
   ]
  },
  {
   "title": "Inbox Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_sc_rollup_node_head_inbox_internal_messages_number{app=\"$node_instance\"}",
     "legendFormat": "Internal messages"
    },
    {
     "expr": "octez_sc_rollup_node_head_inbox_external_messages_number{app=\"$node_instance\"}",
     "legendFormat": "External Messages"
    }
   ]
  },
  {
   "title": "Head process time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_sc_rollup_node_head_inbox_process_time{app=\"$node_instance\"}",
     "legendFormat": "Time (in s)"
    }
   ]
  }
 ]
}