{
 "title": "Tezt Cloud - Layer 1 dashboard",
 "description": "A dashboard for Layer 1 related experiments with tezt cloud",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node stats", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Head level history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(octez_validator_chain_head_level)",
     "legendFormat": "Head level"
    }
   ]
  },
  {
   "title": "Block validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(octez_validator_block_last_finished_request_completion_timestamp-octez_validator_block_last_finished_request_treatment_timestamp)",
     "legendFormat": "Validation time"
    }
   ]
  },
  { "title": "Hardware stats", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "[octez-node] Cpu activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(netdata_app_cpu_utilization_percentage_average{app_group=\"octez-node\",dimension=\"user\"})",
     "legendFormat": "User avg"
    },
    {
     "expr": "avg(netdata_app_cpu_utilization_percentage_average{app_group=\"octez-node\",dimension=\"system\"})",
     "legendFormat": "System avg"
    }
   ]
  },
  {
   "title": "[octez-baker] Cpu activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(netdata_app_cpu_utilization_percentage_average{app_group=\"octez-baker\",dimension=\"user\"})",
     "legendFormat": "User avg"
    },
    {
     "expr": "avg(netdata_app_cpu_utilization_percentage_average{app_group=\"octez-baker\",dimension=\"system\"})",
     "legendFormat": "System avg"
    }
   ]
  },
  {
   "title": "[octez-node] Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "targets": [
    {
     "expr": "avg(netdata_app_mem_usage_MiB_average{app_group=\"octez-node\"})",
     "legendFormat": "RAM avg"
    },
    {
     "expr": "avg(netdata_app_swap_usage_MiB_average{app_group=\"octez-node\"})",
     "legendFormat": "swap avg"
    }
   ]
  },
  {
   "title": "[octez-baker] Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "targets": [
    {
     "expr": "avg(netdata_app_mem_usage_MiB_average{app_group=\"octez-baker\"})",
     "legendFormat": "RAM avg"
    },
    {
     "expr": "avg(netdata_app_swap_usage_MiB_average{app_group=\"octez-baker\"})",
     "legendFormat": "swap avg"
    }
   ]
  },
  {
   "title": "[octez-node] Disk IOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kB/s" } },
   "targets": [
    {
     "expr": "avg(netdata_app_disk_logical_io_KiB_persec_average{app_group=\"octez-node\"})",
     "legendFormat": "Reads avg"
    },
    {
     "expr": "avg(netdata_app_disk_logical_io_KiB_persec_average{app_group=\"octez-node\"})",
     "legendFormat": "Writes avg"
    }
   ]
  },
  {
   "title": "[octez-baker] Disk IOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kB/s" } },
   "targets": [
    {
     "expr": "avg(netdata_app_disk_logical_io_KiB_persec_average{app_group=\"octez-baker\"})",
     "legendFormat": "Reads avg"
    },
    {
     "expr": "avg(netdata_app_disk_logical_io_KiB_persec_average{app_group=\"octez-baker\"})",
     "legendFormat": "Writes avg"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kB/s" } },
   "targets": [
    {
     "expr": "avg(abs(netdata_net_net_kilobits_persec_average{interface_type=\"real\",dimension=\"received\"}) / 8)",
     "legendFormat": "Received avg"
    },
    {
     "expr": "avg(abs(netdata_net_net_kilobits_persec_average{interface_type=\"real\",dimension=\"sent\"}) / 8)",
     "legendFormat": "Transmitted avg"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 43 } },
  {
   "title": "[octez-node] GC maintenance operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg(ocaml_gc_minor_collections)",
     "legendFormat": "Minor collections avg"
    },
    {
     "expr": "avg(ocaml_gc_major_collections)",
     "legendFormat": "Major collections avg"
    },
    {
     "expr": "avg(ocaml_gc_forced_major_collections)",
     "legendFormat": "Forced major collections avg"
    },
    { "expr": "avg(ocaml_gc_compactions)", "legendFormat": "Heap compactions avg" }
   ]
  },
  {
   "title": "[octez-node] GC major word sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "avg(ocaml_gc_heap_words * 8)", "legendFormat": "Major heap avg" }
   ]
  }
 ]
}