# SPDX-FileCopyrightText: 2026 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

.PHONY: update-riscv-pvm
update-riscv-pvm:
	@cargo update octez-riscv octez-riscv-data octez-riscv-durable-storage
