// SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
//
// SPDX-License-Identifier: MIT

use super::CSRegister;

/// [`RootCSRegister`] is the set of unshadowed CSRs, whereas
/// the simple enum [`CSRegister`] is the public-facing API which contains shadowed CSRs.
///
/// For example, sstatus exists as a [`CSRegister`] but the value is actually derived from
/// mstatus, which is also a [`RootCSRegister`]. Similarly for sip/mip, sie/mie, fflags/frm/fcsr.
#[expect(
    non_camel_case_types,
    reason = "We want to use the register names from the RISC-V specification"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, strum::EnumIter, strum::Display)]
pub(super) enum RootCSRegister {
    // Unprivileged Floating-Point CSRs
    fcsr,

    // Unprivileged Counter/Timers
    cycle,
    time,
    instret,
    hpmcounter3,
    hpmcounter4,
    hpmcounter5,
    hpmcounter6,
    hpmcounter7,
    hpmcounter8,
    hpmcounter9,
    hpmcounter10,
    hpmcounter11,
    hpmcounter12,
    hpmcounter13,
    hpmcounter14,
    hpmcounter15,
    hpmcounter16,
    hpmcounter17,
    hpmcounter18,
    hpmcounter19,
    hpmcounter20,
    hpmcounter21,
    hpmcounter22,
    hpmcounter23,
    hpmcounter24,
    hpmcounter25,
    hpmcounter26,
    hpmcounter27,
    hpmcounter28,
    hpmcounter29,
    hpmcounter30,
    hpmcounter31,

    // Supervisor Trap Setup
    stvec,
    scounteren,

    // Supervisor Configuration
    senvcfg,

    // Supervisor Trap Handling
    sscratch,
    sepc,
    scause,
    stval,
    // sip, Shadow of mip

    // Supervisor Protection and Translation
    satp,

    // Supervisor Debug/Trace Registers
    scontext,

    // Hypervisor Trap Setup
    hstatus,
    hedeleg,
    hideleg,
    hie,
    hcounteren,
    hgeie,

    // Hypervisor Trap Handling
    htval,
    hip,
    hvip,
    htinst,
    hgeip,

    // Hypervisor Configuration
    henvcfg,

    // Hypervisor Protection and Translation
    hgatp,

    // Hypervisor Debug/ Trace Registers
    hcontext,

    // Hypervisor Counter/Timer Virtualization Registers
    htimedelta,

    // Virtual Supervisor Registers
    vsstatus,
    vsie,
    vstvec,
    vsscratch,
    vsepc,
    vscause,
    vstval,
    vsip,
    vsatp,

    // Machine Information Registers
    mvendorid,
    marchid,
    mimpid,
    mhartid,
    mconfigptr,

    // Machine Trap Setup
    mstatus,
    misa,
    medeleg,
    mideleg,
    mie,
    mtvec,
    mcounteren,

    // Machine Trap Handling
    mscratch,
    mepc,
    mcause,
    mtval,
    mip,
    mtinst,
    mtval2,

    // Machine Configuration
    menvcfg,
    mseccfg,

    // Machine Memory Protection
    pmpcfg0,
    pmpcfg2,
    pmpcfg4,
    pmpcfg6,
    pmpcfg8,
    pmpcfg10,
    pmpcfg12,
    pmpcfg14,
    pmpaddr0,
    pmpaddr1,
    pmpaddr2,
    pmpaddr3,
    pmpaddr4,
    pmpaddr5,
    pmpaddr6,
    pmpaddr7,
    pmpaddr8,
    pmpaddr9,
    pmpaddr10,
    pmpaddr11,
    pmpaddr12,
    pmpaddr13,
    pmpaddr14,
    pmpaddr15,
    pmpaddr16,
    pmpaddr17,
    pmpaddr18,
    pmpaddr19,
    pmpaddr20,
    pmpaddr21,
    pmpaddr22,
    pmpaddr23,
    pmpaddr24,
    pmpaddr25,
    pmpaddr26,
    pmpaddr27,
    pmpaddr28,
    pmpaddr29,
    pmpaddr30,
    pmpaddr31,
    pmpaddr32,
    pmpaddr33,
    pmpaddr34,
    pmpaddr35,
    pmpaddr36,
    pmpaddr37,
    pmpaddr38,
    pmpaddr39,
    pmpaddr40,
    pmpaddr41,
    pmpaddr42,
    pmpaddr43,
    pmpaddr44,
    pmpaddr45,
    pmpaddr46,
    pmpaddr47,
    pmpaddr48,
    pmpaddr49,
    pmpaddr50,
    pmpaddr51,
    pmpaddr52,
    pmpaddr53,
    pmpaddr54,
    pmpaddr55,
    pmpaddr56,
    pmpaddr57,
    pmpaddr58,
    pmpaddr59,
    pmpaddr60,
    pmpaddr61,
    pmpaddr62,
    pmpaddr63,

    // Machine Non-Maskable Interrupt Handling
    // The draft `Smrnmi` extension is not supported in objdump, printing
    // CSR address directly instead
    mnscratch,
    mnepc,
    mncause,
    mnstatus,

    // Machine Counter/Timers
    mcycle,
    minstret,
    mhpmcounter3,
    mhpmcounter4,
    mhpmcounter5,
    mhpmcounter6,
    mhpmcounter7,
    mhpmcounter8,
    mhpmcounter9,
    mhpmcounter10,
    mhpmcounter11,
    mhpmcounter12,
    mhpmcounter13,
    mhpmcounter14,
    mhpmcounter15,
    mhpmcounter16,
    mhpmcounter17,
    mhpmcounter18,
    mhpmcounter19,
    mhpmcounter20,
    mhpmcounter21,
    mhpmcounter22,
    mhpmcounter23,
    mhpmcounter24,
    mhpmcounter25,
    mhpmcounter26,
    mhpmcounter27,
    mhpmcounter28,
    mhpmcounter29,
    mhpmcounter30,
    mhpmcounter31,

    // Machine Counter Setup
    mcountinhibit,
    mhpmevent3,
    mhpmevent4,
    mhpmevent5,
    mhpmevent6,
    mhpmevent7,
    mhpmevent8,
    mhpmevent9,
    mhpmevent10,
    mhpmevent11,
    mhpmevent12,
    mhpmevent13,
    mhpmevent14,
    mhpmevent15,
    mhpmevent16,
    mhpmevent17,
    mhpmevent18,
    mhpmevent19,
    mhpmevent20,
    mhpmevent21,
    mhpmevent22,
    mhpmevent23,
    mhpmevent24,
    mhpmevent25,
    mhpmevent26,
    mhpmevent27,
    mhpmevent28,
    mhpmevent29,
    mhpmevent30,
    mhpmevent31,

    // Debug/Trace Registers (shared with Debug Mode)
    tselect,
    tdata1,
    tdata2,
    tdata3,
    tcontrol,
    mcontext,

    // Debug Mode Registers
    dcsr,
    dpc,
    dscratch0,
    dscratch1,
}

impl From<CSRegister> for RootCSRegister {
    #[inline(always)]
    fn from(value: CSRegister) -> Self {
        match value {
            // fflags is a shadow of fcsr
            CSRegister::fflags => RootCSRegister::fcsr,
            // frm is a shadow of fcsr
            CSRegister::frm => RootCSRegister::fcsr,
            CSRegister::fcsr => RootCSRegister::fcsr,
            CSRegister::cycle => RootCSRegister::cycle,
            CSRegister::time => RootCSRegister::time,
            CSRegister::instret => RootCSRegister::instret,
            CSRegister::hpmcounter3 => RootCSRegister::hpmcounter3,
            CSRegister::hpmcounter4 => RootCSRegister::hpmcounter4,
            CSRegister::hpmcounter5 => RootCSRegister::hpmcounter5,
            CSRegister::hpmcounter6 => RootCSRegister::hpmcounter6,
            CSRegister::hpmcounter7 => RootCSRegister::hpmcounter7,
            CSRegister::hpmcounter8 => RootCSRegister::hpmcounter8,
            CSRegister::hpmcounter9 => RootCSRegister::hpmcounter9,
            CSRegister::hpmcounter10 => RootCSRegister::hpmcounter10,
            CSRegister::hpmcounter11 => RootCSRegister::hpmcounter11,
            CSRegister::hpmcounter12 => RootCSRegister::hpmcounter12,
            CSRegister::hpmcounter13 => RootCSRegister::hpmcounter13,
            CSRegister::hpmcounter14 => RootCSRegister::hpmcounter14,
            CSRegister::hpmcounter15 => RootCSRegister::hpmcounter15,
            CSRegister::hpmcounter16 => RootCSRegister::hpmcounter16,
            CSRegister::hpmcounter17 => RootCSRegister::hpmcounter17,
            CSRegister::hpmcounter18 => RootCSRegister::hpmcounter18,
            CSRegister::hpmcounter19 => RootCSRegister::hpmcounter19,
            CSRegister::hpmcounter20 => RootCSRegister::hpmcounter20,
            CSRegister::hpmcounter21 => RootCSRegister::hpmcounter21,
            CSRegister::hpmcounter22 => RootCSRegister::hpmcounter22,
            CSRegister::hpmcounter23 => RootCSRegister::hpmcounter23,
            CSRegister::hpmcounter24 => RootCSRegister::hpmcounter24,
            CSRegister::hpmcounter25 => RootCSRegister::hpmcounter25,
            CSRegister::hpmcounter26 => RootCSRegister::hpmcounter26,
            CSRegister::hpmcounter27 => RootCSRegister::hpmcounter27,
            CSRegister::hpmcounter28 => RootCSRegister::hpmcounter28,
            CSRegister::hpmcounter29 => RootCSRegister::hpmcounter29,
            CSRegister::hpmcounter30 => RootCSRegister::hpmcounter30,
            CSRegister::hpmcounter31 => RootCSRegister::hpmcounter31,
            // sstatus is a shadow of mstatus
            CSRegister::sstatus => RootCSRegister::mstatus,
            // sie is a shadow of mie
            CSRegister::sie => RootCSRegister::mie,
            CSRegister::stvec => RootCSRegister::stvec,
            CSRegister::scounteren => RootCSRegister::scounteren,
            CSRegister::senvcfg => RootCSRegister::senvcfg,
            CSRegister::sscratch => RootCSRegister::sscratch,
            CSRegister::sepc => RootCSRegister::sepc,
            CSRegister::scause => RootCSRegister::scause,
            CSRegister::stval => RootCSRegister::stval,
            // sip is a shadow of mip
            CSRegister::sip => RootCSRegister::mip,
            CSRegister::satp => RootCSRegister::satp,
            CSRegister::scontext => RootCSRegister::scontext,
            CSRegister::hstatus => RootCSRegister::hstatus,
            CSRegister::hedeleg => RootCSRegister::hedeleg,
            CSRegister::hideleg => RootCSRegister::hideleg,
            CSRegister::hie => RootCSRegister::hie,
            CSRegister::hcounteren => RootCSRegister::hcounteren,
            CSRegister::hgeie => RootCSRegister::hgeie,
            CSRegister::htval => RootCSRegister::htval,
            CSRegister::hip => RootCSRegister::hip,
            CSRegister::hvip => RootCSRegister::hvip,
            CSRegister::htinst => RootCSRegister::htinst,
            CSRegister::hgeip => RootCSRegister::hgeip,
            CSRegister::henvcfg => RootCSRegister::henvcfg,
            CSRegister::hgatp => RootCSRegister::hgatp,
            CSRegister::hcontext => RootCSRegister::hcontext,
            CSRegister::htimedelta => RootCSRegister::htimedelta,
            CSRegister::vsstatus => RootCSRegister::vsstatus,
            CSRegister::vsie => RootCSRegister::vsie,
            CSRegister::vstvec => RootCSRegister::vstvec,
            CSRegister::vsscratch => RootCSRegister::vsscratch,
            CSRegister::vsepc => RootCSRegister::vsepc,
            CSRegister::vscause => RootCSRegister::vscause,
            CSRegister::vstval => RootCSRegister::vstval,
            CSRegister::vsip => RootCSRegister::vsip,
            CSRegister::vsatp => RootCSRegister::vsatp,
            CSRegister::mvendorid => RootCSRegister::mvendorid,
            CSRegister::marchid => RootCSRegister::marchid,
            CSRegister::mimpid => RootCSRegister::mimpid,
            CSRegister::mhartid => RootCSRegister::mhartid,
            CSRegister::mconfigptr => RootCSRegister::mconfigptr,
            CSRegister::mstatus => RootCSRegister::mstatus,
            CSRegister::misa => RootCSRegister::misa,
            CSRegister::medeleg => RootCSRegister::medeleg,
            CSRegister::mideleg => RootCSRegister::mideleg,
            CSRegister::mie => RootCSRegister::mie,
            CSRegister::mtvec => RootCSRegister::mtvec,
            CSRegister::mcounteren => RootCSRegister::mcounteren,
            CSRegister::mscratch => RootCSRegister::mscratch,
            CSRegister::mepc => RootCSRegister::mepc,
            CSRegister::mcause => RootCSRegister::mcause,
            CSRegister::mtval => RootCSRegister::mtval,
            CSRegister::mip => RootCSRegister::mip,
            CSRegister::mtinst => RootCSRegister::mtinst,
            CSRegister::mtval2 => RootCSRegister::mtval2,
            CSRegister::menvcfg => RootCSRegister::menvcfg,
            CSRegister::mseccfg => RootCSRegister::mseccfg,
            CSRegister::pmpcfg0 => RootCSRegister::pmpcfg0,
            CSRegister::pmpcfg2 => RootCSRegister::pmpcfg2,
            CSRegister::pmpcfg4 => RootCSRegister::pmpcfg4,
            CSRegister::pmpcfg6 => RootCSRegister::pmpcfg6,
            CSRegister::pmpcfg8 => RootCSRegister::pmpcfg8,
            CSRegister::pmpcfg10 => RootCSRegister::pmpcfg10,
            CSRegister::pmpcfg12 => RootCSRegister::pmpcfg12,
            CSRegister::pmpcfg14 => RootCSRegister::pmpcfg14,
            CSRegister::pmpaddr0 => RootCSRegister::pmpaddr0,
            CSRegister::pmpaddr1 => RootCSRegister::pmpaddr1,
            CSRegister::pmpaddr2 => RootCSRegister::pmpaddr2,
            CSRegister::pmpaddr3 => RootCSRegister::pmpaddr3,
            CSRegister::pmpaddr4 => RootCSRegister::pmpaddr4,
            CSRegister::pmpaddr5 => RootCSRegister::pmpaddr5,
            CSRegister::pmpaddr6 => RootCSRegister::pmpaddr6,
            CSRegister::pmpaddr7 => RootCSRegister::pmpaddr7,
            CSRegister::pmpaddr8 => RootCSRegister::pmpaddr8,
            CSRegister::pmpaddr9 => RootCSRegister::pmpaddr9,
            CSRegister::pmpaddr10 => RootCSRegister::pmpaddr10,
            CSRegister::pmpaddr11 => RootCSRegister::pmpaddr11,
            CSRegister::pmpaddr12 => RootCSRegister::pmpaddr12,
            CSRegister::pmpaddr13 => RootCSRegister::pmpaddr13,
            CSRegister::pmpaddr14 => RootCSRegister::pmpaddr14,
            CSRegister::pmpaddr15 => RootCSRegister::pmpaddr15,
            CSRegister::pmpaddr16 => RootCSRegister::pmpaddr16,
            CSRegister::pmpaddr17 => RootCSRegister::pmpaddr17,
            CSRegister::pmpaddr18 => RootCSRegister::pmpaddr18,
            CSRegister::pmpaddr19 => RootCSRegister::pmpaddr19,
            CSRegister::pmpaddr20 => RootCSRegister::pmpaddr20,
            CSRegister::pmpaddr21 => RootCSRegister::pmpaddr21,
            CSRegister::pmpaddr22 => RootCSRegister::pmpaddr22,
            CSRegister::pmpaddr23 => RootCSRegister::pmpaddr23,
            CSRegister::pmpaddr24 => RootCSRegister::pmpaddr24,
            CSRegister::pmpaddr25 => RootCSRegister::pmpaddr25,
            CSRegister::pmpaddr26 => RootCSRegister::pmpaddr26,
            CSRegister::pmpaddr27 => RootCSRegister::pmpaddr27,
            CSRegister::pmpaddr28 => RootCSRegister::pmpaddr28,
            CSRegister::pmpaddr29 => RootCSRegister::pmpaddr29,
            CSRegister::pmpaddr30 => RootCSRegister::pmpaddr30,
            CSRegister::pmpaddr31 => RootCSRegister::pmpaddr31,
            CSRegister::pmpaddr32 => RootCSRegister::pmpaddr32,
            CSRegister::pmpaddr33 => RootCSRegister::pmpaddr33,
            CSRegister::pmpaddr34 => RootCSRegister::pmpaddr34,
            CSRegister::pmpaddr35 => RootCSRegister::pmpaddr35,
            CSRegister::pmpaddr36 => RootCSRegister::pmpaddr36,
            CSRegister::pmpaddr37 => RootCSRegister::pmpaddr37,
            CSRegister::pmpaddr38 => RootCSRegister::pmpaddr38,
            CSRegister::pmpaddr39 => RootCSRegister::pmpaddr39,
            CSRegister::pmpaddr40 => RootCSRegister::pmpaddr40,
            CSRegister::pmpaddr41 => RootCSRegister::pmpaddr41,
            CSRegister::pmpaddr42 => RootCSRegister::pmpaddr42,
            CSRegister::pmpaddr43 => RootCSRegister::pmpaddr43,
            CSRegister::pmpaddr44 => RootCSRegister::pmpaddr44,
            CSRegister::pmpaddr45 => RootCSRegister::pmpaddr45,
            CSRegister::pmpaddr46 => RootCSRegister::pmpaddr46,
            CSRegister::pmpaddr47 => RootCSRegister::pmpaddr47,
            CSRegister::pmpaddr48 => RootCSRegister::pmpaddr48,
            CSRegister::pmpaddr49 => RootCSRegister::pmpaddr49,
            CSRegister::pmpaddr50 => RootCSRegister::pmpaddr50,
            CSRegister::pmpaddr51 => RootCSRegister::pmpaddr51,
            CSRegister::pmpaddr52 => RootCSRegister::pmpaddr52,
            CSRegister::pmpaddr53 => RootCSRegister::pmpaddr53,
            CSRegister::pmpaddr54 => RootCSRegister::pmpaddr54,
            CSRegister::pmpaddr55 => RootCSRegister::pmpaddr55,
            CSRegister::pmpaddr56 => RootCSRegister::pmpaddr56,
            CSRegister::pmpaddr57 => RootCSRegister::pmpaddr57,
            CSRegister::pmpaddr58 => RootCSRegister::pmpaddr58,
            CSRegister::pmpaddr59 => RootCSRegister::pmpaddr59,
            CSRegister::pmpaddr60 => RootCSRegister::pmpaddr60,
            CSRegister::pmpaddr61 => RootCSRegister::pmpaddr61,
            CSRegister::pmpaddr62 => RootCSRegister::pmpaddr62,
            CSRegister::pmpaddr63 => RootCSRegister::pmpaddr63,
            CSRegister::mnscratch => RootCSRegister::mnscratch,
            CSRegister::mnepc => RootCSRegister::mnepc,
            CSRegister::mncause => RootCSRegister::mncause,
            CSRegister::mnstatus => RootCSRegister::mnstatus,
            CSRegister::mcycle => RootCSRegister::mcycle,
            CSRegister::minstret => RootCSRegister::minstret,
            CSRegister::mhpmcounter3 => RootCSRegister::mhpmcounter3,
            CSRegister::mhpmcounter4 => RootCSRegister::mhpmcounter4,
            CSRegister::mhpmcounter5 => RootCSRegister::mhpmcounter5,
            CSRegister::mhpmcounter6 => RootCSRegister::mhpmcounter6,
            CSRegister::mhpmcounter7 => RootCSRegister::mhpmcounter7,
            CSRegister::mhpmcounter8 => RootCSRegister::mhpmcounter8,
            CSRegister::mhpmcounter9 => RootCSRegister::mhpmcounter9,
            CSRegister::mhpmcounter10 => RootCSRegister::mhpmcounter10,
            CSRegister::mhpmcounter11 => RootCSRegister::mhpmcounter11,
            CSRegister::mhpmcounter12 => RootCSRegister::mhpmcounter12,
            CSRegister::mhpmcounter13 => RootCSRegister::mhpmcounter13,
            CSRegister::mhpmcounter14 => RootCSRegister::mhpmcounter14,
            CSRegister::mhpmcounter15 => RootCSRegister::mhpmcounter15,
            CSRegister::mhpmcounter16 => RootCSRegister::mhpmcounter16,
            CSRegister::mhpmcounter17 => RootCSRegister::mhpmcounter17,
            CSRegister::mhpmcounter18 => RootCSRegister::mhpmcounter18,
            CSRegister::mhpmcounter19 => RootCSRegister::mhpmcounter19,
            CSRegister::mhpmcounter20 => RootCSRegister::mhpmcounter20,
            CSRegister::mhpmcounter21 => RootCSRegister::mhpmcounter21,
            CSRegister::mhpmcounter22 => RootCSRegister::mhpmcounter22,
            CSRegister::mhpmcounter23 => RootCSRegister::mhpmcounter23,
            CSRegister::mhpmcounter24 => RootCSRegister::mhpmcounter24,
            CSRegister::mhpmcounter25 => RootCSRegister::mhpmcounter25,
            CSRegister::mhpmcounter26 => RootCSRegister::mhpmcounter26,
            CSRegister::mhpmcounter27 => RootCSRegister::mhpmcounter27,
            CSRegister::mhpmcounter28 => RootCSRegister::mhpmcounter28,
            CSRegister::mhpmcounter29 => RootCSRegister::mhpmcounter29,
            CSRegister::mhpmcounter30 => RootCSRegister::mhpmcounter30,
            CSRegister::mhpmcounter31 => RootCSRegister::mhpmcounter31,
            CSRegister::mcountinhibit => RootCSRegister::mcountinhibit,
            CSRegister::mhpmevent3 => RootCSRegister::mhpmevent3,
            CSRegister::mhpmevent4 => RootCSRegister::mhpmevent4,
            CSRegister::mhpmevent5 => RootCSRegister::mhpmevent5,
            CSRegister::mhpmevent6 => RootCSRegister::mhpmevent6,
            CSRegister::mhpmevent7 => RootCSRegister::mhpmevent7,
            CSRegister::mhpmevent8 => RootCSRegister::mhpmevent8,
            CSRegister::mhpmevent9 => RootCSRegister::mhpmevent9,
            CSRegister::mhpmevent10 => RootCSRegister::mhpmevent10,
            CSRegister::mhpmevent11 => RootCSRegister::mhpmevent11,
            CSRegister::mhpmevent12 => RootCSRegister::mhpmevent12,
            CSRegister::mhpmevent13 => RootCSRegister::mhpmevent13,
            CSRegister::mhpmevent14 => RootCSRegister::mhpmevent14,
            CSRegister::mhpmevent15 => RootCSRegister::mhpmevent15,
            CSRegister::mhpmevent16 => RootCSRegister::mhpmevent16,
            CSRegister::mhpmevent17 => RootCSRegister::mhpmevent17,
            CSRegister::mhpmevent18 => RootCSRegister::mhpmevent18,
            CSRegister::mhpmevent19 => RootCSRegister::mhpmevent19,
            CSRegister::mhpmevent20 => RootCSRegister::mhpmevent20,
            CSRegister::mhpmevent21 => RootCSRegister::mhpmevent21,
            CSRegister::mhpmevent22 => RootCSRegister::mhpmevent22,
            CSRegister::mhpmevent23 => RootCSRegister::mhpmevent23,
            CSRegister::mhpmevent24 => RootCSRegister::mhpmevent24,
            CSRegister::mhpmevent25 => RootCSRegister::mhpmevent25,
            CSRegister::mhpmevent26 => RootCSRegister::mhpmevent26,
            CSRegister::mhpmevent27 => RootCSRegister::mhpmevent27,
            CSRegister::mhpmevent28 => RootCSRegister::mhpmevent28,
            CSRegister::mhpmevent29 => RootCSRegister::mhpmevent29,
            CSRegister::mhpmevent30 => RootCSRegister::mhpmevent30,
            CSRegister::mhpmevent31 => RootCSRegister::mhpmevent31,
            CSRegister::tselect => RootCSRegister::tselect,
            CSRegister::tdata1 => RootCSRegister::tdata1,
            CSRegister::tdata2 => RootCSRegister::tdata2,
            CSRegister::tdata3 => RootCSRegister::tdata3,
            CSRegister::tcontrol => RootCSRegister::tcontrol,
            CSRegister::mcontext => RootCSRegister::mcontext,
            CSRegister::dcsr => RootCSRegister::dcsr,
            CSRegister::dpc => RootCSRegister::dpc,
            CSRegister::dscratch0 => RootCSRegister::dscratch0,
            CSRegister::dscratch1 => RootCSRegister::dscratch1,
        }
    }
}
