// SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
//
// SPDX-License-Identifier: MIT

mod mstatus;

use super::{
    effects::{handle_csr_effect, NoEffect, XipEffect},
    root::RootCSRegister,
    CSRegisters,
};
use crate::{
    bits::Bits64,
    state_backend::{AllocatedOf, EffectCell, EffectCellLayout},
};
use mstatus::MStatusLayout;
pub(super) use mstatus::MStatusValue;

/// Representation of a value in a CSR
pub type CSRRepr = u64;

/// Value of a Control or State register
#[derive(
    Copy,
    Clone,
    Debug,
    derive_more::Display,
    derive_more::From,
    derive_more::Into,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[repr(transparent)]
pub struct CSRValue(CSRRepr);

impl CSRValue {
    /// Access the underlying representation.
    pub fn repr(self) -> CSRRepr {
        self.0
    }
}

impl Bits64 for CSRValue {
    const WIDTH: usize = CSRRepr::WIDTH;

    fn from_bits(value: u64) -> Self {
        Self(value)
    }

    fn to_bits(&self) -> u64 {
        self.repr()
    }
}

macro_rules! csregisters_boilerplate {
    (
        $struct_v:vis struct $struct_t:ident where layout $layout_t:ty {
            $($vis:vis $name:ident: $cell_repr:ty),+
            $( , )?
        }
    ) => {
        $struct_v struct $struct_t <M>
        where
            M: $crate::state_backend::ManagerBase,
        {
            $($vis $name: $cell_repr,)+
        }

        impl<M: $crate::state_backend::ManagerBase> $struct_t<M> {
            pub fn bind(space: AllocatedOf<$layout_t, M>) -> Self {
                Self {
                    $($name: <$cell_repr>::bind(space.$name),)+
                }
            }
        }

        impl<M: $crate::state_backend::ManagerBase> CSRegisters<M> {
            // Methods for operating on a generic CSRegister (used by csrrw/csrrci etc)
            // Not public since they are used only as an abstraction by [CSRegisters]
            #[inline(always)]
            pub(super) fn general_raw_read(&self, csr: RootCSRegister) -> CSRRepr
            where
                M: $crate::state_backend::ManagerRead,
            {
                match csr {
                    $( RootCSRegister::$name => self.registers.$name.read() ),+
                }
            }

            #[inline(always)]
            pub(super) fn general_raw_write(&mut self, csr: RootCSRegister, value: CSRRepr)
            where
                M: $crate::state_backend::ManagerWrite,
            {
                let effect = match csr {
                    $( RootCSRegister::$name => self.registers.$name.write(value) ),+
                };

                handle_csr_effect(self, effect);
            }

            #[inline(always)]
            pub(super) fn general_raw_replace(&mut self, csr: RootCSRegister, value: CSRRepr) -> CSRRepr
            where
                M: $crate::state_backend::ManagerReadWrite,
            {
                let (old_value, effect) = match csr {
                    $( RootCSRegister::$name => self.registers.$name.replace(value) ),+
                };

                handle_csr_effect(self, effect);
                old_value
            }
        }
    };
}

type NoEffectCSR<M> = EffectCell<CSRRepr, NoEffect, M>;
type MipEffectCSR<M> = EffectCell<CSRRepr, XipEffect, M>;

type EffectCSRLayout = EffectCellLayout<CSRRepr>;

csregisters_boilerplate!(
    pub(super) struct CSRegisterValues where layout CSRValuesLayout {
        pub(super) mstatus: MStatusValue<M>,
        pub(super) mip: MipEffectCSR<M>,

        mnscratch: NoEffectCSR<M>,
        mnepc: NoEffectCSR<M>,
        mncause: NoEffectCSR<M>,
        mnstatus: NoEffectCSR<M>,
        cycle: NoEffectCSR<M>,
        time: NoEffectCSR<M>,
        instret: NoEffectCSR<M>,
        mcycle: NoEffectCSR<M>,
        minstret: NoEffectCSR<M>,
        hpmcounter3: NoEffectCSR<M>,
        hpmcounter4: NoEffectCSR<M>,
        hpmcounter5: NoEffectCSR<M>,
        hpmcounter6: NoEffectCSR<M>,
        hpmcounter7: NoEffectCSR<M>,
        hpmcounter8: NoEffectCSR<M>,
        hpmcounter9: NoEffectCSR<M>,
        hpmcounter10: NoEffectCSR<M>,
        hpmcounter11: NoEffectCSR<M>,
        hpmcounter12: NoEffectCSR<M>,
        hpmcounter13: NoEffectCSR<M>,
        hpmcounter14: NoEffectCSR<M>,
        hpmcounter15: NoEffectCSR<M>,
        hpmcounter16: NoEffectCSR<M>,
        hpmcounter17: NoEffectCSR<M>,
        hpmcounter18: NoEffectCSR<M>,
        hpmcounter19: NoEffectCSR<M>,
        hpmcounter20: NoEffectCSR<M>,
        hpmcounter21: NoEffectCSR<M>,
        hpmcounter22: NoEffectCSR<M>,
        hpmcounter23: NoEffectCSR<M>,
        hpmcounter24: NoEffectCSR<M>,
        hpmcounter25: NoEffectCSR<M>,
        hpmcounter26: NoEffectCSR<M>,
        hpmcounter27: NoEffectCSR<M>,
        hpmcounter28: NoEffectCSR<M>,
        hpmcounter29: NoEffectCSR<M>,
        hpmcounter30: NoEffectCSR<M>,
        hpmcounter31: NoEffectCSR<M>,
        mhpmcounter3: NoEffectCSR<M>,
        mhpmcounter4: NoEffectCSR<M>,
        mhpmcounter5: NoEffectCSR<M>,
        mhpmcounter6: NoEffectCSR<M>,
        mhpmcounter7: NoEffectCSR<M>,
        mhpmcounter8: NoEffectCSR<M>,
        mhpmcounter9: NoEffectCSR<M>,
        mhpmcounter10: NoEffectCSR<M>,
        mhpmcounter11: NoEffectCSR<M>,
        mhpmcounter12: NoEffectCSR<M>,
        mhpmcounter13: NoEffectCSR<M>,
        mhpmcounter14: NoEffectCSR<M>,
        mhpmcounter15: NoEffectCSR<M>,
        mhpmcounter16: NoEffectCSR<M>,
        mhpmcounter17: NoEffectCSR<M>,
        mhpmcounter18: NoEffectCSR<M>,
        mhpmcounter19: NoEffectCSR<M>,
        mhpmcounter20: NoEffectCSR<M>,
        mhpmcounter21: NoEffectCSR<M>,
        mhpmcounter22: NoEffectCSR<M>,
        mhpmcounter23: NoEffectCSR<M>,
        mhpmcounter24: NoEffectCSR<M>,
        mhpmcounter25: NoEffectCSR<M>,
        mhpmcounter26: NoEffectCSR<M>,
        mhpmcounter27: NoEffectCSR<M>,
        mhpmcounter28: NoEffectCSR<M>,
        mhpmcounter29: NoEffectCSR<M>,
        mhpmcounter30: NoEffectCSR<M>,
        mhpmcounter31: NoEffectCSR<M>,
        mhpmevent3: NoEffectCSR<M>,
        mhpmevent4: NoEffectCSR<M>,
        mhpmevent5: NoEffectCSR<M>,
        mhpmevent6: NoEffectCSR<M>,
        mhpmevent7: NoEffectCSR<M>,
        mhpmevent8: NoEffectCSR<M>,
        mhpmevent9: NoEffectCSR<M>,
        mhpmevent10: NoEffectCSR<M>,
        mhpmevent11: NoEffectCSR<M>,
        mhpmevent12: NoEffectCSR<M>,
        mhpmevent13: NoEffectCSR<M>,
        mhpmevent14: NoEffectCSR<M>,
        mhpmevent15: NoEffectCSR<M>,
        mhpmevent16: NoEffectCSR<M>,
        mhpmevent17: NoEffectCSR<M>,
        mhpmevent18: NoEffectCSR<M>,
        mhpmevent19: NoEffectCSR<M>,
        mhpmevent20: NoEffectCSR<M>,
        mhpmevent21: NoEffectCSR<M>,
        mhpmevent22: NoEffectCSR<M>,
        mhpmevent23: NoEffectCSR<M>,
        mhpmevent24: NoEffectCSR<M>,
        mhpmevent25: NoEffectCSR<M>,
        mhpmevent26: NoEffectCSR<M>,
        mhpmevent27: NoEffectCSR<M>,
        mhpmevent28: NoEffectCSR<M>,
        mhpmevent29: NoEffectCSR<M>,
        mhpmevent30: NoEffectCSR<M>,
        mhpmevent31: NoEffectCSR<M>,
        mcountinhibit: NoEffectCSR<M>,
        scounteren: NoEffectCSR<M>,
        mcounteren: NoEffectCSR<M>,
        pub(super) fcsr: NoEffectCSR<M>,
        pmpcfg0: NoEffectCSR<M>,
        pmpcfg2: NoEffectCSR<M>,
        pmpcfg4: NoEffectCSR<M>,
        pmpcfg6: NoEffectCSR<M>,
        pmpcfg8: NoEffectCSR<M>,
        pmpcfg10: NoEffectCSR<M>,
        pmpcfg12: NoEffectCSR<M>,
        pmpcfg14: NoEffectCSR<M>,
        pmpaddr0: NoEffectCSR<M>,
        pmpaddr1: NoEffectCSR<M>,
        pmpaddr2: NoEffectCSR<M>,
        pmpaddr3: NoEffectCSR<M>,
        pmpaddr4: NoEffectCSR<M>,
        pmpaddr5: NoEffectCSR<M>,
        pmpaddr6: NoEffectCSR<M>,
        pmpaddr7: NoEffectCSR<M>,
        pmpaddr8: NoEffectCSR<M>,
        pmpaddr9: NoEffectCSR<M>,
        pmpaddr10: NoEffectCSR<M>,
        pmpaddr11: NoEffectCSR<M>,
        pmpaddr12: NoEffectCSR<M>,
        pmpaddr13: NoEffectCSR<M>,
        pmpaddr14: NoEffectCSR<M>,
        pmpaddr15: NoEffectCSR<M>,
        pmpaddr16: NoEffectCSR<M>,
        pmpaddr17: NoEffectCSR<M>,
        pmpaddr18: NoEffectCSR<M>,
        pmpaddr19: NoEffectCSR<M>,
        pmpaddr20: NoEffectCSR<M>,
        pmpaddr21: NoEffectCSR<M>,
        pmpaddr22: NoEffectCSR<M>,
        pmpaddr23: NoEffectCSR<M>,
        pmpaddr24: NoEffectCSR<M>,
        pmpaddr25: NoEffectCSR<M>,
        pmpaddr26: NoEffectCSR<M>,
        pmpaddr27: NoEffectCSR<M>,
        pmpaddr28: NoEffectCSR<M>,
        pmpaddr29: NoEffectCSR<M>,
        pmpaddr30: NoEffectCSR<M>,
        pmpaddr31: NoEffectCSR<M>,
        pmpaddr32: NoEffectCSR<M>,
        pmpaddr33: NoEffectCSR<M>,
        pmpaddr34: NoEffectCSR<M>,
        pmpaddr35: NoEffectCSR<M>,
        pmpaddr36: NoEffectCSR<M>,
        pmpaddr37: NoEffectCSR<M>,
        pmpaddr38: NoEffectCSR<M>,
        pmpaddr39: NoEffectCSR<M>,
        pmpaddr40: NoEffectCSR<M>,
        pmpaddr41: NoEffectCSR<M>,
        pmpaddr42: NoEffectCSR<M>,
        pmpaddr43: NoEffectCSR<M>,
        pmpaddr44: NoEffectCSR<M>,
        pmpaddr45: NoEffectCSR<M>,
        pmpaddr46: NoEffectCSR<M>,
        pmpaddr47: NoEffectCSR<M>,
        pmpaddr48: NoEffectCSR<M>,
        pmpaddr49: NoEffectCSR<M>,
        pmpaddr50: NoEffectCSR<M>,
        pmpaddr51: NoEffectCSR<M>,
        pmpaddr52: NoEffectCSR<M>,
        pmpaddr53: NoEffectCSR<M>,
        pmpaddr54: NoEffectCSR<M>,
        pmpaddr55: NoEffectCSR<M>,
        pmpaddr56: NoEffectCSR<M>,
        pmpaddr57: NoEffectCSR<M>,
        pmpaddr58: NoEffectCSR<M>,
        pmpaddr59: NoEffectCSR<M>,
        pmpaddr60: NoEffectCSR<M>,
        pmpaddr61: NoEffectCSR<M>,
        pmpaddr62: NoEffectCSR<M>,
        pmpaddr63: NoEffectCSR<M>,
        mhartid: NoEffectCSR<M>,
        mvendorid: NoEffectCSR<M>,
        marchid: NoEffectCSR<M>,
        mimpid: NoEffectCSR<M>,
        misa: NoEffectCSR<M>,
        mscratch: NoEffectCSR<M>,
        sscratch: NoEffectCSR<M>,
        stvec: NoEffectCSR<M>,
        mtvec: NoEffectCSR<M>,
        pub(super) mie: NoEffectCSR<M>,
        satp: NoEffectCSR<M>,
        scause: NoEffectCSR<M>,
        mcause: NoEffectCSR<M>,
        sepc: NoEffectCSR<M>,
        mepc: NoEffectCSR<M>,
        stval: NoEffectCSR<M>,
        mtval: NoEffectCSR<M>,
        mtval2: NoEffectCSR<M>,
        mtinst: NoEffectCSR<M>,
        senvcfg: NoEffectCSR<M>,
        menvcfg: NoEffectCSR<M>,
        mconfigptr: NoEffectCSR<M>,
        medeleg: NoEffectCSR<M>,
        mideleg: NoEffectCSR<M>,
        mseccfg: NoEffectCSR<M>,
        scontext: NoEffectCSR<M>,
        hstatus: NoEffectCSR<M>,
        hedeleg: NoEffectCSR<M>,
        hideleg: NoEffectCSR<M>,
        hie: NoEffectCSR<M>,
        hcounteren: NoEffectCSR<M>,
        hgeie: NoEffectCSR<M>,
        htval: NoEffectCSR<M>,
        hip: NoEffectCSR<M>,
        hvip: NoEffectCSR<M>,
        htinst: NoEffectCSR<M>,
        hgeip: NoEffectCSR<M>,
        henvcfg: NoEffectCSR<M>,
        hgatp: NoEffectCSR<M>,
        hcontext: NoEffectCSR<M>,
        htimedelta: NoEffectCSR<M>,
        vsstatus: NoEffectCSR<M>,
        vsie: NoEffectCSR<M>,
        vstvec: NoEffectCSR<M>,
        vsscratch: NoEffectCSR<M>,
        vsepc: NoEffectCSR<M>,
        vscause: NoEffectCSR<M>,
        vstval: NoEffectCSR<M>,
        vsip: NoEffectCSR<M>,
        vsatp: NoEffectCSR<M>,
        tselect: NoEffectCSR<M>,
        tdata1: NoEffectCSR<M>,
        tdata2: NoEffectCSR<M>,
        tdata3: NoEffectCSR<M>,
        tcontrol: NoEffectCSR<M>,
        mcontext: NoEffectCSR<M>,
        dcsr: NoEffectCSR<M>,
        dpc: NoEffectCSR<M>,
        dscratch0: NoEffectCSR<M>,
        dscratch1: NoEffectCSR<M>,
    }
);

pub struct CSRValuesLayout {
    _mstatus: MStatusLayout,
    _mnscratch: EffectCSRLayout,
    _mnepc: EffectCSRLayout,
    _mncause: EffectCSRLayout,
    _mnstatus: EffectCSRLayout,
    _cycle: EffectCSRLayout,
    _time: EffectCSRLayout,
    _instret: EffectCSRLayout,
    _mcycle: EffectCSRLayout,
    _minstret: EffectCSRLayout,
    _hpmcounter3: EffectCSRLayout,
    _hpmcounter4: EffectCSRLayout,
    _hpmcounter5: EffectCSRLayout,
    _hpmcounter6: EffectCSRLayout,
    _hpmcounter7: EffectCSRLayout,
    _hpmcounter8: EffectCSRLayout,
    _hpmcounter9: EffectCSRLayout,
    _hpmcounter10: EffectCSRLayout,
    _hpmcounter11: EffectCSRLayout,
    _hpmcounter12: EffectCSRLayout,
    _hpmcounter13: EffectCSRLayout,
    _hpmcounter14: EffectCSRLayout,
    _hpmcounter15: EffectCSRLayout,
    _hpmcounter16: EffectCSRLayout,
    _hpmcounter17: EffectCSRLayout,
    _hpmcounter18: EffectCSRLayout,
    _hpmcounter19: EffectCSRLayout,
    _hpmcounter20: EffectCSRLayout,
    _hpmcounter21: EffectCSRLayout,
    _hpmcounter22: EffectCSRLayout,
    _hpmcounter23: EffectCSRLayout,
    _hpmcounter24: EffectCSRLayout,
    _hpmcounter25: EffectCSRLayout,
    _hpmcounter26: EffectCSRLayout,
    _hpmcounter27: EffectCSRLayout,
    _hpmcounter28: EffectCSRLayout,
    _hpmcounter29: EffectCSRLayout,
    _hpmcounter30: EffectCSRLayout,
    _hpmcounter31: EffectCSRLayout,
    _mhpmcounter3: EffectCSRLayout,
    _mhpmcounter4: EffectCSRLayout,
    _mhpmcounter5: EffectCSRLayout,
    _mhpmcounter6: EffectCSRLayout,
    _mhpmcounter7: EffectCSRLayout,
    _mhpmcounter8: EffectCSRLayout,
    _mhpmcounter9: EffectCSRLayout,
    _mhpmcounter10: EffectCSRLayout,
    _mhpmcounter11: EffectCSRLayout,
    _mhpmcounter12: EffectCSRLayout,
    _mhpmcounter13: EffectCSRLayout,
    _mhpmcounter14: EffectCSRLayout,
    _mhpmcounter15: EffectCSRLayout,
    _mhpmcounter16: EffectCSRLayout,
    _mhpmcounter17: EffectCSRLayout,
    _mhpmcounter18: EffectCSRLayout,
    _mhpmcounter19: EffectCSRLayout,
    _mhpmcounter20: EffectCSRLayout,
    _mhpmcounter21: EffectCSRLayout,
    _mhpmcounter22: EffectCSRLayout,
    _mhpmcounter23: EffectCSRLayout,
    _mhpmcounter24: EffectCSRLayout,
    _mhpmcounter25: EffectCSRLayout,
    _mhpmcounter26: EffectCSRLayout,
    _mhpmcounter27: EffectCSRLayout,
    _mhpmcounter28: EffectCSRLayout,
    _mhpmcounter29: EffectCSRLayout,
    _mhpmcounter30: EffectCSRLayout,
    _mhpmcounter31: EffectCSRLayout,
    _mhpmevent3: EffectCSRLayout,
    _mhpmevent4: EffectCSRLayout,
    _mhpmevent5: EffectCSRLayout,
    _mhpmevent6: EffectCSRLayout,
    _mhpmevent7: EffectCSRLayout,
    _mhpmevent8: EffectCSRLayout,
    _mhpmevent9: EffectCSRLayout,
    _mhpmevent10: EffectCSRLayout,
    _mhpmevent11: EffectCSRLayout,
    _mhpmevent12: EffectCSRLayout,
    _mhpmevent13: EffectCSRLayout,
    _mhpmevent14: EffectCSRLayout,
    _mhpmevent15: EffectCSRLayout,
    _mhpmevent16: EffectCSRLayout,
    _mhpmevent17: EffectCSRLayout,
    _mhpmevent18: EffectCSRLayout,
    _mhpmevent19: EffectCSRLayout,
    _mhpmevent20: EffectCSRLayout,
    _mhpmevent21: EffectCSRLayout,
    _mhpmevent22: EffectCSRLayout,
    _mhpmevent23: EffectCSRLayout,
    _mhpmevent24: EffectCSRLayout,
    _mhpmevent25: EffectCSRLayout,
    _mhpmevent26: EffectCSRLayout,
    _mhpmevent27: EffectCSRLayout,
    _mhpmevent28: EffectCSRLayout,
    _mhpmevent29: EffectCSRLayout,
    _mhpmevent30: EffectCSRLayout,
    _mhpmevent31: EffectCSRLayout,
    _mcountinhibit: EffectCSRLayout,
    _scounteren: EffectCSRLayout,
    _mcounteren: EffectCSRLayout,
    _fcsr: EffectCSRLayout,
    _pmpcfg0: EffectCSRLayout,
    _pmpcfg2: EffectCSRLayout,
    _pmpcfg4: EffectCSRLayout,
    _pmpcfg6: EffectCSRLayout,
    _pmpcfg8: EffectCSRLayout,
    _pmpcfg10: EffectCSRLayout,
    _pmpcfg12: EffectCSRLayout,
    _pmpcfg14: EffectCSRLayout,
    _pmpaddr0: EffectCSRLayout,
    _pmpaddr1: EffectCSRLayout,
    _pmpaddr2: EffectCSRLayout,
    _pmpaddr3: EffectCSRLayout,
    _pmpaddr4: EffectCSRLayout,
    _pmpaddr5: EffectCSRLayout,
    _pmpaddr6: EffectCSRLayout,
    _pmpaddr7: EffectCSRLayout,
    _pmpaddr8: EffectCSRLayout,
    _pmpaddr9: EffectCSRLayout,
    _pmpaddr10: EffectCSRLayout,
    _pmpaddr11: EffectCSRLayout,
    _pmpaddr12: EffectCSRLayout,
    _pmpaddr13: EffectCSRLayout,
    _pmpaddr14: EffectCSRLayout,
    _pmpaddr15: EffectCSRLayout,
    _pmpaddr16: EffectCSRLayout,
    _pmpaddr17: EffectCSRLayout,
    _pmpaddr18: EffectCSRLayout,
    _pmpaddr19: EffectCSRLayout,
    _pmpaddr20: EffectCSRLayout,
    _pmpaddr21: EffectCSRLayout,
    _pmpaddr22: EffectCSRLayout,
    _pmpaddr23: EffectCSRLayout,
    _pmpaddr24: EffectCSRLayout,
    _pmpaddr25: EffectCSRLayout,
    _pmpaddr26: EffectCSRLayout,
    _pmpaddr27: EffectCSRLayout,
    _pmpaddr28: EffectCSRLayout,
    _pmpaddr29: EffectCSRLayout,
    _pmpaddr30: EffectCSRLayout,
    _pmpaddr31: EffectCSRLayout,
    _pmpaddr32: EffectCSRLayout,
    _pmpaddr33: EffectCSRLayout,
    _pmpaddr34: EffectCSRLayout,
    _pmpaddr35: EffectCSRLayout,
    _pmpaddr36: EffectCSRLayout,
    _pmpaddr37: EffectCSRLayout,
    _pmpaddr38: EffectCSRLayout,
    _pmpaddr39: EffectCSRLayout,
    _pmpaddr40: EffectCSRLayout,
    _pmpaddr41: EffectCSRLayout,
    _pmpaddr42: EffectCSRLayout,
    _pmpaddr43: EffectCSRLayout,
    _pmpaddr44: EffectCSRLayout,
    _pmpaddr45: EffectCSRLayout,
    _pmpaddr46: EffectCSRLayout,
    _pmpaddr47: EffectCSRLayout,
    _pmpaddr48: EffectCSRLayout,
    _pmpaddr49: EffectCSRLayout,
    _pmpaddr50: EffectCSRLayout,
    _pmpaddr51: EffectCSRLayout,
    _pmpaddr52: EffectCSRLayout,
    _pmpaddr53: EffectCSRLayout,
    _pmpaddr54: EffectCSRLayout,
    _pmpaddr55: EffectCSRLayout,
    _pmpaddr56: EffectCSRLayout,
    _pmpaddr57: EffectCSRLayout,
    _pmpaddr58: EffectCSRLayout,
    _pmpaddr59: EffectCSRLayout,
    _pmpaddr60: EffectCSRLayout,
    _pmpaddr61: EffectCSRLayout,
    _pmpaddr62: EffectCSRLayout,
    _pmpaddr63: EffectCSRLayout,
    _mhartid: EffectCSRLayout,
    _mvendorid: EffectCSRLayout,
    _marchid: EffectCSRLayout,
    _mimpid: EffectCSRLayout,
    _misa: EffectCSRLayout,
    _mscratch: EffectCSRLayout,
    _sscratch: EffectCSRLayout,
    _stvec: EffectCSRLayout,
    _mtvec: EffectCSRLayout,
    _mie: EffectCSRLayout,
    _satp: EffectCSRLayout,
    _scause: EffectCSRLayout,
    _mcause: EffectCSRLayout,
    _sepc: EffectCSRLayout,
    _mepc: EffectCSRLayout,
    _stval: EffectCSRLayout,
    _mtval: EffectCSRLayout,
    _mtval2: EffectCSRLayout,
    _mip: EffectCSRLayout,
    _mtinst: EffectCSRLayout,
    _senvcfg: EffectCSRLayout,
    _menvcfg: EffectCSRLayout,
    _mconfigptr: EffectCSRLayout,
    _medeleg: EffectCSRLayout,
    _mideleg: EffectCSRLayout,
    _mseccfg: EffectCSRLayout,
    _scontext: EffectCSRLayout,
    _hstatus: EffectCSRLayout,
    _hedeleg: EffectCSRLayout,
    _hideleg: EffectCSRLayout,
    _hie: EffectCSRLayout,
    _hcounteren: EffectCSRLayout,
    _hgeie: EffectCSRLayout,
    _htval: EffectCSRLayout,
    _hip: EffectCSRLayout,
    _hvip: EffectCSRLayout,
    _htinst: EffectCSRLayout,
    _hgeip: EffectCSRLayout,
    _henvcfg: EffectCSRLayout,
    _hgatp: EffectCSRLayout,
    _hcontext: EffectCSRLayout,
    _htimedelta: EffectCSRLayout,
    _vsstatus: EffectCSRLayout,
    _vsie: EffectCSRLayout,
    _vstvec: EffectCSRLayout,
    _vsscratch: EffectCSRLayout,
    _vsepc: EffectCSRLayout,
    _vscause: EffectCSRLayout,
    _vstval: EffectCSRLayout,
    _vsip: EffectCSRLayout,
    _vsatp: EffectCSRLayout,
    _tselect: EffectCSRLayout,
    _tdata1: EffectCSRLayout,
    _tdata2: EffectCSRLayout,
    _tdata3: EffectCSRLayout,
    _tcontrol: EffectCSRLayout,
    _mcontext: EffectCSRLayout,
    _dcsr: EffectCSRLayout,
    _dpc: EffectCSRLayout,
    _dscratch0: EffectCSRLayout,
    _dscratch1: EffectCSRLayout,
}

pub struct CSRValuesPlaced {
    mstatus: crate::state_backend::PlacedOf<MStatusLayout>,
    mnscratch: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mnepc: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mncause: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mnstatus: crate::state_backend::PlacedOf<EffectCSRLayout>,
    cycle: crate::state_backend::PlacedOf<EffectCSRLayout>,
    time: crate::state_backend::PlacedOf<EffectCSRLayout>,
    instret: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mcycle: crate::state_backend::PlacedOf<EffectCSRLayout>,
    minstret: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter3: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter4: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter5: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter6: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter7: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter8: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter9: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter10: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter11: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter12: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter13: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter14: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter15: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter16: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter17: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter18: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter19: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter20: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter21: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter22: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter23: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter24: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter25: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter26: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter27: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter28: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter29: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter30: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hpmcounter31: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter3: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter4: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter5: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter6: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter7: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter8: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter9: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter10: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter11: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter12: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter13: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter14: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter15: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter16: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter17: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter18: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter19: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter20: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter21: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter22: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter23: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter24: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter25: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter26: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter27: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter28: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter29: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter30: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmcounter31: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent3: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent4: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent5: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent6: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent7: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent8: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent9: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent10: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent11: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent12: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent13: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent14: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent15: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent16: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent17: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent18: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent19: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent20: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent21: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent22: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent23: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent24: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent25: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent26: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent27: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent28: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent29: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent30: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhpmevent31: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mcountinhibit: crate::state_backend::PlacedOf<EffectCSRLayout>,
    scounteren: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mcounteren: crate::state_backend::PlacedOf<EffectCSRLayout>,
    fcsr: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg0: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg2: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg4: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg6: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg8: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg10: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg12: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpcfg14: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr0: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr1: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr2: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr3: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr4: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr5: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr6: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr7: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr8: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr9: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr10: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr11: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr12: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr13: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr14: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr15: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr16: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr17: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr18: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr19: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr20: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr21: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr22: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr23: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr24: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr25: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr26: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr27: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr28: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr29: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr30: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr31: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr32: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr33: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr34: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr35: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr36: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr37: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr38: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr39: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr40: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr41: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr42: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr43: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr44: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr45: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr46: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr47: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr48: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr49: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr50: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr51: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr52: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr53: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr54: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr55: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr56: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr57: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr58: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr59: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr60: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr61: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr62: crate::state_backend::PlacedOf<EffectCSRLayout>,
    pmpaddr63: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mhartid: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mvendorid: crate::state_backend::PlacedOf<EffectCSRLayout>,
    marchid: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mimpid: crate::state_backend::PlacedOf<EffectCSRLayout>,
    misa: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mscratch: crate::state_backend::PlacedOf<EffectCSRLayout>,
    sscratch: crate::state_backend::PlacedOf<EffectCSRLayout>,
    stvec: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mtvec: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mie: crate::state_backend::PlacedOf<EffectCSRLayout>,
    satp: crate::state_backend::PlacedOf<EffectCSRLayout>,
    scause: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mcause: crate::state_backend::PlacedOf<EffectCSRLayout>,
    sepc: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mepc: crate::state_backend::PlacedOf<EffectCSRLayout>,
    stval: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mtval: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mtval2: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mip: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mtinst: crate::state_backend::PlacedOf<EffectCSRLayout>,
    senvcfg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    menvcfg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mconfigptr: crate::state_backend::PlacedOf<EffectCSRLayout>,
    medeleg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mideleg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mseccfg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    scontext: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hstatus: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hedeleg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hideleg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hie: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hcounteren: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hgeie: crate::state_backend::PlacedOf<EffectCSRLayout>,
    htval: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hip: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hvip: crate::state_backend::PlacedOf<EffectCSRLayout>,
    htinst: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hgeip: crate::state_backend::PlacedOf<EffectCSRLayout>,
    henvcfg: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hgatp: crate::state_backend::PlacedOf<EffectCSRLayout>,
    hcontext: crate::state_backend::PlacedOf<EffectCSRLayout>,
    htimedelta: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vsstatus: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vsie: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vstvec: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vsscratch: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vsepc: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vscause: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vstval: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vsip: crate::state_backend::PlacedOf<EffectCSRLayout>,
    vsatp: crate::state_backend::PlacedOf<EffectCSRLayout>,
    tselect: crate::state_backend::PlacedOf<EffectCSRLayout>,
    tdata1: crate::state_backend::PlacedOf<EffectCSRLayout>,
    tdata2: crate::state_backend::PlacedOf<EffectCSRLayout>,
    tdata3: crate::state_backend::PlacedOf<EffectCSRLayout>,
    tcontrol: crate::state_backend::PlacedOf<EffectCSRLayout>,
    mcontext: crate::state_backend::PlacedOf<EffectCSRLayout>,
    dcsr: crate::state_backend::PlacedOf<EffectCSRLayout>,
    dpc: crate::state_backend::PlacedOf<EffectCSRLayout>,
    dscratch0: crate::state_backend::PlacedOf<EffectCSRLayout>,
    dscratch1: crate::state_backend::PlacedOf<EffectCSRLayout>,
}

pub struct CSRValuesAllocated<M: crate::state_backend::ManagerBase> {
    mstatus: AllocatedOf<MStatusLayout, M>,
    mnscratch: AllocatedOf<EffectCSRLayout, M>,
    mnepc: AllocatedOf<EffectCSRLayout, M>,
    mncause: AllocatedOf<EffectCSRLayout, M>,
    mnstatus: AllocatedOf<EffectCSRLayout, M>,
    cycle: AllocatedOf<EffectCSRLayout, M>,
    time: AllocatedOf<EffectCSRLayout, M>,
    instret: AllocatedOf<EffectCSRLayout, M>,
    mcycle: AllocatedOf<EffectCSRLayout, M>,
    minstret: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter3: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter4: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter5: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter6: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter7: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter8: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter9: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter10: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter11: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter12: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter13: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter14: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter15: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter16: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter17: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter18: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter19: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter20: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter21: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter22: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter23: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter24: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter25: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter26: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter27: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter28: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter29: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter30: AllocatedOf<EffectCSRLayout, M>,
    hpmcounter31: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter3: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter4: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter5: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter6: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter7: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter8: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter9: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter10: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter11: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter12: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter13: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter14: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter15: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter16: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter17: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter18: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter19: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter20: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter21: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter22: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter23: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter24: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter25: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter26: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter27: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter28: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter29: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter30: AllocatedOf<EffectCSRLayout, M>,
    mhpmcounter31: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent3: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent4: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent5: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent6: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent7: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent8: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent9: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent10: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent11: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent12: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent13: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent14: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent15: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent16: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent17: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent18: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent19: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent20: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent21: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent22: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent23: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent24: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent25: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent26: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent27: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent28: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent29: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent30: AllocatedOf<EffectCSRLayout, M>,
    mhpmevent31: AllocatedOf<EffectCSRLayout, M>,
    mcountinhibit: AllocatedOf<EffectCSRLayout, M>,
    scounteren: AllocatedOf<EffectCSRLayout, M>,
    mcounteren: AllocatedOf<EffectCSRLayout, M>,
    fcsr: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg0: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg2: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg4: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg6: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg8: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg10: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg12: AllocatedOf<EffectCSRLayout, M>,
    pmpcfg14: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr0: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr1: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr2: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr3: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr4: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr5: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr6: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr7: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr8: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr9: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr10: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr11: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr12: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr13: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr14: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr15: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr16: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr17: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr18: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr19: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr20: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr21: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr22: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr23: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr24: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr25: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr26: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr27: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr28: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr29: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr30: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr31: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr32: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr33: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr34: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr35: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr36: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr37: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr38: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr39: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr40: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr41: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr42: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr43: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr44: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr45: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr46: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr47: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr48: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr49: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr50: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr51: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr52: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr53: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr54: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr55: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr56: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr57: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr58: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr59: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr60: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr61: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr62: AllocatedOf<EffectCSRLayout, M>,
    pmpaddr63: AllocatedOf<EffectCSRLayout, M>,
    mhartid: AllocatedOf<EffectCSRLayout, M>,
    mvendorid: AllocatedOf<EffectCSRLayout, M>,
    marchid: AllocatedOf<EffectCSRLayout, M>,
    mimpid: AllocatedOf<EffectCSRLayout, M>,
    misa: AllocatedOf<EffectCSRLayout, M>,
    mscratch: AllocatedOf<EffectCSRLayout, M>,
    sscratch: AllocatedOf<EffectCSRLayout, M>,
    stvec: AllocatedOf<EffectCSRLayout, M>,
    mtvec: AllocatedOf<EffectCSRLayout, M>,
    mie: AllocatedOf<EffectCSRLayout, M>,
    satp: AllocatedOf<EffectCSRLayout, M>,
    scause: AllocatedOf<EffectCSRLayout, M>,
    mcause: AllocatedOf<EffectCSRLayout, M>,
    sepc: AllocatedOf<EffectCSRLayout, M>,
    mepc: AllocatedOf<EffectCSRLayout, M>,
    stval: AllocatedOf<EffectCSRLayout, M>,
    mtval: AllocatedOf<EffectCSRLayout, M>,
    mtval2: AllocatedOf<EffectCSRLayout, M>,
    mip: AllocatedOf<EffectCSRLayout, M>,
    mtinst: AllocatedOf<EffectCSRLayout, M>,
    senvcfg: AllocatedOf<EffectCSRLayout, M>,
    menvcfg: AllocatedOf<EffectCSRLayout, M>,
    mconfigptr: AllocatedOf<EffectCSRLayout, M>,
    medeleg: AllocatedOf<EffectCSRLayout, M>,
    mideleg: AllocatedOf<EffectCSRLayout, M>,
    mseccfg: AllocatedOf<EffectCSRLayout, M>,
    scontext: AllocatedOf<EffectCSRLayout, M>,
    hstatus: AllocatedOf<EffectCSRLayout, M>,
    hedeleg: AllocatedOf<EffectCSRLayout, M>,
    hideleg: AllocatedOf<EffectCSRLayout, M>,
    hie: AllocatedOf<EffectCSRLayout, M>,
    hcounteren: AllocatedOf<EffectCSRLayout, M>,
    hgeie: AllocatedOf<EffectCSRLayout, M>,
    htval: AllocatedOf<EffectCSRLayout, M>,
    hip: AllocatedOf<EffectCSRLayout, M>,
    hvip: AllocatedOf<EffectCSRLayout, M>,
    htinst: AllocatedOf<EffectCSRLayout, M>,
    hgeip: AllocatedOf<EffectCSRLayout, M>,
    henvcfg: AllocatedOf<EffectCSRLayout, M>,
    hgatp: AllocatedOf<EffectCSRLayout, M>,
    hcontext: AllocatedOf<EffectCSRLayout, M>,
    htimedelta: AllocatedOf<EffectCSRLayout, M>,
    vsstatus: AllocatedOf<EffectCSRLayout, M>,
    vsie: AllocatedOf<EffectCSRLayout, M>,
    vstvec: AllocatedOf<EffectCSRLayout, M>,
    vsscratch: AllocatedOf<EffectCSRLayout, M>,
    vsepc: AllocatedOf<EffectCSRLayout, M>,
    vscause: AllocatedOf<EffectCSRLayout, M>,
    vstval: AllocatedOf<EffectCSRLayout, M>,
    vsip: AllocatedOf<EffectCSRLayout, M>,
    vsatp: AllocatedOf<EffectCSRLayout, M>,
    tselect: AllocatedOf<EffectCSRLayout, M>,
    tdata1: AllocatedOf<EffectCSRLayout, M>,
    tdata2: AllocatedOf<EffectCSRLayout, M>,
    tdata3: AllocatedOf<EffectCSRLayout, M>,
    tcontrol: AllocatedOf<EffectCSRLayout, M>,
    mcontext: AllocatedOf<EffectCSRLayout, M>,
    dcsr: AllocatedOf<EffectCSRLayout, M>,
    dpc: AllocatedOf<EffectCSRLayout, M>,
    dscratch0: AllocatedOf<EffectCSRLayout, M>,
    dscratch1: AllocatedOf<EffectCSRLayout, M>,
}

impl crate::state_backend::Layout for CSRValuesLayout {
    type Placed = CSRValuesPlaced;

    type Allocated<M: crate::state_backend::ManagerBase> = CSRValuesAllocated<M>;

    fn place_with(alloc: &mut crate::state_backend::Choreographer) -> Self::Placed {
        CSRValuesPlaced {
            mstatus: <MStatusLayout>::place_with(alloc),
            mnscratch: <EffectCSRLayout>::place_with(alloc),
            mnepc: <EffectCSRLayout>::place_with(alloc),
            mncause: <EffectCSRLayout>::place_with(alloc),
            mnstatus: <EffectCSRLayout>::place_with(alloc),
            cycle: <EffectCSRLayout>::place_with(alloc),
            time: <EffectCSRLayout>::place_with(alloc),
            instret: <EffectCSRLayout>::place_with(alloc),
            mcycle: <EffectCSRLayout>::place_with(alloc),
            minstret: <EffectCSRLayout>::place_with(alloc),
            hpmcounter3: <EffectCSRLayout>::place_with(alloc),
            hpmcounter4: <EffectCSRLayout>::place_with(alloc),
            hpmcounter5: <EffectCSRLayout>::place_with(alloc),
            hpmcounter6: <EffectCSRLayout>::place_with(alloc),
            hpmcounter7: <EffectCSRLayout>::place_with(alloc),
            hpmcounter8: <EffectCSRLayout>::place_with(alloc),
            hpmcounter9: <EffectCSRLayout>::place_with(alloc),
            hpmcounter10: <EffectCSRLayout>::place_with(alloc),
            hpmcounter11: <EffectCSRLayout>::place_with(alloc),
            hpmcounter12: <EffectCSRLayout>::place_with(alloc),
            hpmcounter13: <EffectCSRLayout>::place_with(alloc),
            hpmcounter14: <EffectCSRLayout>::place_with(alloc),
            hpmcounter15: <EffectCSRLayout>::place_with(alloc),
            hpmcounter16: <EffectCSRLayout>::place_with(alloc),
            hpmcounter17: <EffectCSRLayout>::place_with(alloc),
            hpmcounter18: <EffectCSRLayout>::place_with(alloc),
            hpmcounter19: <EffectCSRLayout>::place_with(alloc),
            hpmcounter20: <EffectCSRLayout>::place_with(alloc),
            hpmcounter21: <EffectCSRLayout>::place_with(alloc),
            hpmcounter22: <EffectCSRLayout>::place_with(alloc),
            hpmcounter23: <EffectCSRLayout>::place_with(alloc),
            hpmcounter24: <EffectCSRLayout>::place_with(alloc),
            hpmcounter25: <EffectCSRLayout>::place_with(alloc),
            hpmcounter26: <EffectCSRLayout>::place_with(alloc),
            hpmcounter27: <EffectCSRLayout>::place_with(alloc),
            hpmcounter28: <EffectCSRLayout>::place_with(alloc),
            hpmcounter29: <EffectCSRLayout>::place_with(alloc),
            hpmcounter30: <EffectCSRLayout>::place_with(alloc),
            hpmcounter31: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter3: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter4: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter5: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter6: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter7: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter8: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter9: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter10: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter11: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter12: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter13: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter14: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter15: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter16: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter17: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter18: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter19: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter20: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter21: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter22: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter23: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter24: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter25: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter26: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter27: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter28: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter29: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter30: <EffectCSRLayout>::place_with(alloc),
            mhpmcounter31: <EffectCSRLayout>::place_with(alloc),
            mhpmevent3: <EffectCSRLayout>::place_with(alloc),
            mhpmevent4: <EffectCSRLayout>::place_with(alloc),
            mhpmevent5: <EffectCSRLayout>::place_with(alloc),
            mhpmevent6: <EffectCSRLayout>::place_with(alloc),
            mhpmevent7: <EffectCSRLayout>::place_with(alloc),
            mhpmevent8: <EffectCSRLayout>::place_with(alloc),
            mhpmevent9: <EffectCSRLayout>::place_with(alloc),
            mhpmevent10: <EffectCSRLayout>::place_with(alloc),
            mhpmevent11: <EffectCSRLayout>::place_with(alloc),
            mhpmevent12: <EffectCSRLayout>::place_with(alloc),
            mhpmevent13: <EffectCSRLayout>::place_with(alloc),
            mhpmevent14: <EffectCSRLayout>::place_with(alloc),
            mhpmevent15: <EffectCSRLayout>::place_with(alloc),
            mhpmevent16: <EffectCSRLayout>::place_with(alloc),
            mhpmevent17: <EffectCSRLayout>::place_with(alloc),
            mhpmevent18: <EffectCSRLayout>::place_with(alloc),
            mhpmevent19: <EffectCSRLayout>::place_with(alloc),
            mhpmevent20: <EffectCSRLayout>::place_with(alloc),
            mhpmevent21: <EffectCSRLayout>::place_with(alloc),
            mhpmevent22: <EffectCSRLayout>::place_with(alloc),
            mhpmevent23: <EffectCSRLayout>::place_with(alloc),
            mhpmevent24: <EffectCSRLayout>::place_with(alloc),
            mhpmevent25: <EffectCSRLayout>::place_with(alloc),
            mhpmevent26: <EffectCSRLayout>::place_with(alloc),
            mhpmevent27: <EffectCSRLayout>::place_with(alloc),
            mhpmevent28: <EffectCSRLayout>::place_with(alloc),
            mhpmevent29: <EffectCSRLayout>::place_with(alloc),
            mhpmevent30: <EffectCSRLayout>::place_with(alloc),
            mhpmevent31: <EffectCSRLayout>::place_with(alloc),
            mcountinhibit: <EffectCSRLayout>::place_with(alloc),
            scounteren: <EffectCSRLayout>::place_with(alloc),
            mcounteren: <EffectCSRLayout>::place_with(alloc),
            fcsr: <EffectCSRLayout>::place_with(alloc),
            pmpcfg0: <EffectCSRLayout>::place_with(alloc),
            pmpcfg2: <EffectCSRLayout>::place_with(alloc),
            pmpcfg4: <EffectCSRLayout>::place_with(alloc),
            pmpcfg6: <EffectCSRLayout>::place_with(alloc),
            pmpcfg8: <EffectCSRLayout>::place_with(alloc),
            pmpcfg10: <EffectCSRLayout>::place_with(alloc),
            pmpcfg12: <EffectCSRLayout>::place_with(alloc),
            pmpcfg14: <EffectCSRLayout>::place_with(alloc),
            pmpaddr0: <EffectCSRLayout>::place_with(alloc),
            pmpaddr1: <EffectCSRLayout>::place_with(alloc),
            pmpaddr2: <EffectCSRLayout>::place_with(alloc),
            pmpaddr3: <EffectCSRLayout>::place_with(alloc),
            pmpaddr4: <EffectCSRLayout>::place_with(alloc),
            pmpaddr5: <EffectCSRLayout>::place_with(alloc),
            pmpaddr6: <EffectCSRLayout>::place_with(alloc),
            pmpaddr7: <EffectCSRLayout>::place_with(alloc),
            pmpaddr8: <EffectCSRLayout>::place_with(alloc),
            pmpaddr9: <EffectCSRLayout>::place_with(alloc),
            pmpaddr10: <EffectCSRLayout>::place_with(alloc),
            pmpaddr11: <EffectCSRLayout>::place_with(alloc),
            pmpaddr12: <EffectCSRLayout>::place_with(alloc),
            pmpaddr13: <EffectCSRLayout>::place_with(alloc),
            pmpaddr14: <EffectCSRLayout>::place_with(alloc),
            pmpaddr15: <EffectCSRLayout>::place_with(alloc),
            pmpaddr16: <EffectCSRLayout>::place_with(alloc),
            pmpaddr17: <EffectCSRLayout>::place_with(alloc),
            pmpaddr18: <EffectCSRLayout>::place_with(alloc),
            pmpaddr19: <EffectCSRLayout>::place_with(alloc),
            pmpaddr20: <EffectCSRLayout>::place_with(alloc),
            pmpaddr21: <EffectCSRLayout>::place_with(alloc),
            pmpaddr22: <EffectCSRLayout>::place_with(alloc),
            pmpaddr23: <EffectCSRLayout>::place_with(alloc),
            pmpaddr24: <EffectCSRLayout>::place_with(alloc),
            pmpaddr25: <EffectCSRLayout>::place_with(alloc),
            pmpaddr26: <EffectCSRLayout>::place_with(alloc),
            pmpaddr27: <EffectCSRLayout>::place_with(alloc),
            pmpaddr28: <EffectCSRLayout>::place_with(alloc),
            pmpaddr29: <EffectCSRLayout>::place_with(alloc),
            pmpaddr30: <EffectCSRLayout>::place_with(alloc),
            pmpaddr31: <EffectCSRLayout>::place_with(alloc),
            pmpaddr32: <EffectCSRLayout>::place_with(alloc),
            pmpaddr33: <EffectCSRLayout>::place_with(alloc),
            pmpaddr34: <EffectCSRLayout>::place_with(alloc),
            pmpaddr35: <EffectCSRLayout>::place_with(alloc),
            pmpaddr36: <EffectCSRLayout>::place_with(alloc),
            pmpaddr37: <EffectCSRLayout>::place_with(alloc),
            pmpaddr38: <EffectCSRLayout>::place_with(alloc),
            pmpaddr39: <EffectCSRLayout>::place_with(alloc),
            pmpaddr40: <EffectCSRLayout>::place_with(alloc),
            pmpaddr41: <EffectCSRLayout>::place_with(alloc),
            pmpaddr42: <EffectCSRLayout>::place_with(alloc),
            pmpaddr43: <EffectCSRLayout>::place_with(alloc),
            pmpaddr44: <EffectCSRLayout>::place_with(alloc),
            pmpaddr45: <EffectCSRLayout>::place_with(alloc),
            pmpaddr46: <EffectCSRLayout>::place_with(alloc),
            pmpaddr47: <EffectCSRLayout>::place_with(alloc),
            pmpaddr48: <EffectCSRLayout>::place_with(alloc),
            pmpaddr49: <EffectCSRLayout>::place_with(alloc),
            pmpaddr50: <EffectCSRLayout>::place_with(alloc),
            pmpaddr51: <EffectCSRLayout>::place_with(alloc),
            pmpaddr52: <EffectCSRLayout>::place_with(alloc),
            pmpaddr53: <EffectCSRLayout>::place_with(alloc),
            pmpaddr54: <EffectCSRLayout>::place_with(alloc),
            pmpaddr55: <EffectCSRLayout>::place_with(alloc),
            pmpaddr56: <EffectCSRLayout>::place_with(alloc),
            pmpaddr57: <EffectCSRLayout>::place_with(alloc),
            pmpaddr58: <EffectCSRLayout>::place_with(alloc),
            pmpaddr59: <EffectCSRLayout>::place_with(alloc),
            pmpaddr60: <EffectCSRLayout>::place_with(alloc),
            pmpaddr61: <EffectCSRLayout>::place_with(alloc),
            pmpaddr62: <EffectCSRLayout>::place_with(alloc),
            pmpaddr63: <EffectCSRLayout>::place_with(alloc),
            mhartid: <EffectCSRLayout>::place_with(alloc),
            mvendorid: <EffectCSRLayout>::place_with(alloc),
            marchid: <EffectCSRLayout>::place_with(alloc),
            mimpid: <EffectCSRLayout>::place_with(alloc),
            misa: <EffectCSRLayout>::place_with(alloc),
            mscratch: <EffectCSRLayout>::place_with(alloc),
            sscratch: <EffectCSRLayout>::place_with(alloc),
            stvec: <EffectCSRLayout>::place_with(alloc),
            mtvec: <EffectCSRLayout>::place_with(alloc),
            mie: <EffectCSRLayout>::place_with(alloc),
            satp: <EffectCSRLayout>::place_with(alloc),
            scause: <EffectCSRLayout>::place_with(alloc),
            mcause: <EffectCSRLayout>::place_with(alloc),
            sepc: <EffectCSRLayout>::place_with(alloc),
            mepc: <EffectCSRLayout>::place_with(alloc),
            stval: <EffectCSRLayout>::place_with(alloc),
            mtval: <EffectCSRLayout>::place_with(alloc),
            mtval2: <EffectCSRLayout>::place_with(alloc),
            mip: <EffectCSRLayout>::place_with(alloc),
            mtinst: <EffectCSRLayout>::place_with(alloc),
            senvcfg: <EffectCSRLayout>::place_with(alloc),
            menvcfg: <EffectCSRLayout>::place_with(alloc),
            mconfigptr: <EffectCSRLayout>::place_with(alloc),
            medeleg: <EffectCSRLayout>::place_with(alloc),
            mideleg: <EffectCSRLayout>::place_with(alloc),
            mseccfg: <EffectCSRLayout>::place_with(alloc),
            scontext: <EffectCSRLayout>::place_with(alloc),
            hstatus: <EffectCSRLayout>::place_with(alloc),
            hedeleg: <EffectCSRLayout>::place_with(alloc),
            hideleg: <EffectCSRLayout>::place_with(alloc),
            hie: <EffectCSRLayout>::place_with(alloc),
            hcounteren: <EffectCSRLayout>::place_with(alloc),
            hgeie: <EffectCSRLayout>::place_with(alloc),
            htval: <EffectCSRLayout>::place_with(alloc),
            hip: <EffectCSRLayout>::place_with(alloc),
            hvip: <EffectCSRLayout>::place_with(alloc),
            htinst: <EffectCSRLayout>::place_with(alloc),
            hgeip: <EffectCSRLayout>::place_with(alloc),
            henvcfg: <EffectCSRLayout>::place_with(alloc),
            hgatp: <EffectCSRLayout>::place_with(alloc),
            hcontext: <EffectCSRLayout>::place_with(alloc),
            htimedelta: <EffectCSRLayout>::place_with(alloc),
            vsstatus: <EffectCSRLayout>::place_with(alloc),
            vsie: <EffectCSRLayout>::place_with(alloc),
            vstvec: <EffectCSRLayout>::place_with(alloc),
            vsscratch: <EffectCSRLayout>::place_with(alloc),
            vsepc: <EffectCSRLayout>::place_with(alloc),
            vscause: <EffectCSRLayout>::place_with(alloc),
            vstval: <EffectCSRLayout>::place_with(alloc),
            vsip: <EffectCSRLayout>::place_with(alloc),
            vsatp: <EffectCSRLayout>::place_with(alloc),
            tselect: <EffectCSRLayout>::place_with(alloc),
            tdata1: <EffectCSRLayout>::place_with(alloc),
            tdata2: <EffectCSRLayout>::place_with(alloc),
            tdata3: <EffectCSRLayout>::place_with(alloc),
            tcontrol: <EffectCSRLayout>::place_with(alloc),
            mcontext: <EffectCSRLayout>::place_with(alloc),
            dcsr: <EffectCSRLayout>::place_with(alloc),
            dpc: <EffectCSRLayout>::place_with(alloc),
            dscratch0: <EffectCSRLayout>::place_with(alloc),
            dscratch1: <EffectCSRLayout>::place_with(alloc),
        }
    }

    fn allocate<M: crate::state_backend::ManagerAlloc>(
        backend: &mut M,
        placed: Self::Placed,
    ) -> Self::Allocated<M> {
        Self::Allocated {
            mstatus: <MStatusLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mstatus,
            ),
            mnscratch: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mnscratch,
            ),
            mnepc: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mnepc,
            ),
            mncause: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mncause,
            ),
            mnstatus: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mnstatus,
            ),
            cycle: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.cycle,
            ),
            time: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.time),
            instret: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.instret,
            ),
            mcycle: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mcycle,
            ),
            minstret: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.minstret,
            ),
            hpmcounter3: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter3,
            ),
            hpmcounter4: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter4,
            ),
            hpmcounter5: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter5,
            ),
            hpmcounter6: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter6,
            ),
            hpmcounter7: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter7,
            ),
            hpmcounter8: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter8,
            ),
            hpmcounter9: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter9,
            ),
            hpmcounter10: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter10,
            ),
            hpmcounter11: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter11,
            ),
            hpmcounter12: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter12,
            ),
            hpmcounter13: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter13,
            ),
            hpmcounter14: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter14,
            ),
            hpmcounter15: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter15,
            ),
            hpmcounter16: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter16,
            ),
            hpmcounter17: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter17,
            ),
            hpmcounter18: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter18,
            ),
            hpmcounter19: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter19,
            ),
            hpmcounter20: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter20,
            ),
            hpmcounter21: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter21,
            ),
            hpmcounter22: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter22,
            ),
            hpmcounter23: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter23,
            ),
            hpmcounter24: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter24,
            ),
            hpmcounter25: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter25,
            ),
            hpmcounter26: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter26,
            ),
            hpmcounter27: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter27,
            ),
            hpmcounter28: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter28,
            ),
            hpmcounter29: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter29,
            ),
            hpmcounter30: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter30,
            ),
            hpmcounter31: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hpmcounter31,
            ),
            mhpmcounter3: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter3,
            ),
            mhpmcounter4: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter4,
            ),
            mhpmcounter5: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter5,
            ),
            mhpmcounter6: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter6,
            ),
            mhpmcounter7: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter7,
            ),
            mhpmcounter8: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter8,
            ),
            mhpmcounter9: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter9,
            ),
            mhpmcounter10: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter10,
            ),
            mhpmcounter11: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter11,
            ),
            mhpmcounter12: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter12,
            ),
            mhpmcounter13: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter13,
            ),
            mhpmcounter14: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter14,
            ),
            mhpmcounter15: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter15,
            ),
            mhpmcounter16: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter16,
            ),
            mhpmcounter17: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter17,
            ),
            mhpmcounter18: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter18,
            ),
            mhpmcounter19: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter19,
            ),
            mhpmcounter20: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter20,
            ),
            mhpmcounter21: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter21,
            ),
            mhpmcounter22: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter22,
            ),
            mhpmcounter23: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter23,
            ),
            mhpmcounter24: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter24,
            ),
            mhpmcounter25: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter25,
            ),
            mhpmcounter26: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter26,
            ),
            mhpmcounter27: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter27,
            ),
            mhpmcounter28: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter28,
            ),
            mhpmcounter29: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter29,
            ),
            mhpmcounter30: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter30,
            ),
            mhpmcounter31: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmcounter31,
            ),
            mhpmevent3: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent3,
            ),
            mhpmevent4: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent4,
            ),
            mhpmevent5: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent5,
            ),
            mhpmevent6: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent6,
            ),
            mhpmevent7: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent7,
            ),
            mhpmevent8: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent8,
            ),
            mhpmevent9: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent9,
            ),
            mhpmevent10: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent10,
            ),
            mhpmevent11: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent11,
            ),
            mhpmevent12: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent12,
            ),
            mhpmevent13: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent13,
            ),
            mhpmevent14: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent14,
            ),
            mhpmevent15: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent15,
            ),
            mhpmevent16: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent16,
            ),
            mhpmevent17: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent17,
            ),
            mhpmevent18: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent18,
            ),
            mhpmevent19: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent19,
            ),
            mhpmevent20: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent20,
            ),
            mhpmevent21: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent21,
            ),
            mhpmevent22: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent22,
            ),
            mhpmevent23: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent23,
            ),
            mhpmevent24: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent24,
            ),
            mhpmevent25: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent25,
            ),
            mhpmevent26: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent26,
            ),
            mhpmevent27: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent27,
            ),
            mhpmevent28: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent28,
            ),
            mhpmevent29: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent29,
            ),
            mhpmevent30: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent30,
            ),
            mhpmevent31: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhpmevent31,
            ),
            mcountinhibit: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mcountinhibit,
            ),
            scounteren: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.scounteren,
            ),
            mcounteren: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mcounteren,
            ),
            fcsr: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.fcsr),
            pmpcfg0: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg0,
            ),
            pmpcfg2: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg2,
            ),
            pmpcfg4: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg4,
            ),
            pmpcfg6: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg6,
            ),
            pmpcfg8: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg8,
            ),
            pmpcfg10: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg10,
            ),
            pmpcfg12: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg12,
            ),
            pmpcfg14: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpcfg14,
            ),
            pmpaddr0: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr0,
            ),
            pmpaddr1: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr1,
            ),
            pmpaddr2: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr2,
            ),
            pmpaddr3: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr3,
            ),
            pmpaddr4: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr4,
            ),
            pmpaddr5: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr5,
            ),
            pmpaddr6: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr6,
            ),
            pmpaddr7: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr7,
            ),
            pmpaddr8: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr8,
            ),
            pmpaddr9: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr9,
            ),
            pmpaddr10: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr10,
            ),
            pmpaddr11: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr11,
            ),
            pmpaddr12: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr12,
            ),
            pmpaddr13: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr13,
            ),
            pmpaddr14: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr14,
            ),
            pmpaddr15: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr15,
            ),
            pmpaddr16: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr16,
            ),
            pmpaddr17: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr17,
            ),
            pmpaddr18: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr18,
            ),
            pmpaddr19: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr19,
            ),
            pmpaddr20: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr20,
            ),
            pmpaddr21: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr21,
            ),
            pmpaddr22: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr22,
            ),
            pmpaddr23: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr23,
            ),
            pmpaddr24: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr24,
            ),
            pmpaddr25: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr25,
            ),
            pmpaddr26: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr26,
            ),
            pmpaddr27: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr27,
            ),
            pmpaddr28: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr28,
            ),
            pmpaddr29: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr29,
            ),
            pmpaddr30: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr30,
            ),
            pmpaddr31: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr31,
            ),
            pmpaddr32: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr32,
            ),
            pmpaddr33: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr33,
            ),
            pmpaddr34: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr34,
            ),
            pmpaddr35: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr35,
            ),
            pmpaddr36: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr36,
            ),
            pmpaddr37: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr37,
            ),
            pmpaddr38: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr38,
            ),
            pmpaddr39: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr39,
            ),
            pmpaddr40: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr40,
            ),
            pmpaddr41: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr41,
            ),
            pmpaddr42: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr42,
            ),
            pmpaddr43: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr43,
            ),
            pmpaddr44: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr44,
            ),
            pmpaddr45: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr45,
            ),
            pmpaddr46: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr46,
            ),
            pmpaddr47: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr47,
            ),
            pmpaddr48: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr48,
            ),
            pmpaddr49: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr49,
            ),
            pmpaddr50: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr50,
            ),
            pmpaddr51: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr51,
            ),
            pmpaddr52: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr52,
            ),
            pmpaddr53: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr53,
            ),
            pmpaddr54: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr54,
            ),
            pmpaddr55: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr55,
            ),
            pmpaddr56: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr56,
            ),
            pmpaddr57: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr57,
            ),
            pmpaddr58: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr58,
            ),
            pmpaddr59: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr59,
            ),
            pmpaddr60: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr60,
            ),
            pmpaddr61: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr61,
            ),
            pmpaddr62: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr62,
            ),
            pmpaddr63: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.pmpaddr63,
            ),
            mhartid: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mhartid,
            ),
            mvendorid: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mvendorid,
            ),
            marchid: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.marchid,
            ),
            mimpid: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mimpid,
            ),
            misa: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.misa),
            mscratch: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mscratch,
            ),
            sscratch: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.sscratch,
            ),
            stvec: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.stvec,
            ),
            mtvec: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mtvec,
            ),
            mie: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.mie),
            satp: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.satp),
            scause: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.scause,
            ),
            mcause: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mcause,
            ),
            sepc: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.sepc),
            mepc: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.mepc),
            stval: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.stval,
            ),
            mtval: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mtval,
            ),
            mtval2: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mtval2,
            ),
            mip: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.mip),
            mtinst: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mtinst,
            ),
            senvcfg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.senvcfg,
            ),
            menvcfg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.menvcfg,
            ),
            mconfigptr: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mconfigptr,
            ),
            medeleg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.medeleg,
            ),
            mideleg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mideleg,
            ),
            mseccfg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mseccfg,
            ),
            scontext: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.scontext,
            ),
            hstatus: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hstatus,
            ),
            hedeleg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hedeleg,
            ),
            hideleg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hideleg,
            ),
            hie: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.hie),
            hcounteren: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hcounteren,
            ),
            hgeie: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hgeie,
            ),
            htval: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.htval,
            ),
            hip: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.hip),
            hvip: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.hvip),
            htinst: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.htinst,
            ),
            hgeip: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hgeip,
            ),
            henvcfg: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.henvcfg,
            ),
            hgatp: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hgatp,
            ),
            hcontext: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.hcontext,
            ),
            htimedelta: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.htimedelta,
            ),
            vsstatus: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vsstatus,
            ),
            vsie: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.vsie),
            vstvec: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vstvec,
            ),
            vsscratch: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vsscratch,
            ),
            vsepc: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vsepc,
            ),
            vscause: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vscause,
            ),
            vstval: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vstval,
            ),
            vsip: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.vsip),
            vsatp: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.vsatp,
            ),
            tselect: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.tselect,
            ),
            tdata1: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.tdata1,
            ),
            tdata2: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.tdata2,
            ),
            tdata3: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.tdata3,
            ),
            tcontrol: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.tcontrol,
            ),
            mcontext: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.mcontext,
            ),
            dcsr: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.dcsr),
            dpc: <EffectCSRLayout as crate::state_backend::Layout>::allocate(backend, placed.dpc),
            dscratch0: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.dscratch0,
            ),
            dscratch1: <EffectCSRLayout as crate::state_backend::Layout>::allocate(
                backend,
                placed.dscratch1,
            ),
        }
    }
}
