# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-types"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
thiserror.workspace = true
primitive-types.workspace = true
threshold-encryption.workspace = true

# Encoding
rlp.workspace = true
serde.workspace = true
hex.workspace = true

# Crypto
libsecp256k1.workspace = true

[dev-dependencies]
rand.workspace = true
