/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals
import org.example.tezos.add

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test fun canImportRustFn() {
        assertEquals(3u, add(1u, 2u), "Failed to call rust fun successfully")
    }
}
