.TH OCTEZ-ACCUSER 1 "January 2024" "Octez Accuser Manual"

.SH NAME
octez-accuser \- Octez Accuser Daemon

.SH SYNOPSIS
.B octez-accuser
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B octez-accuser
includes the necessary tools and functionalities for checking the safety of the layer one of the Tezos blockchain.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Octez Documentation: https://tezos.gitlab.io/shell/cli-commands.html

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
