.TH OCTEZ-SIGNER 1 "January 2024" "Octez Signer Manual"

.SH NAME
octez-signer \- Octez Remote signer

.SH SYNOPSIS
.B octez-signer
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B octez-signer
 provides the essential tools and functionalities for securely signing
 transactions, blocks, and other protocol-related data within the Tezos
 network.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Octez Documentation: https://tezos.gitlab.io/shell/cli-commands.html

.SH AUTHOR
Nomadic Labs.

.SH COPYRIGHT
Copyright \(co 2024 Nomadic Labs.

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
