.TH OCTEZ-BAKER 1 "January 2024" "Octez Baker Manual"

.SH NAME
octez-baker \- Octez Baker Daemon

.SH SYNOPSIS
.B octez-baker
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B octez-baker
includes the necessary tools and functionalities for participating in the
baking process, such as block creation, endorsement, and protocol-specific
consensus mechanisms.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Octez Documentation: https://tezos.gitlab.io/shell/cli-commands.html

.SH AUTHOR
Nomadic Labs.

.SH COPYRIGHT
Copyright \(co 2024 Nomadic Labs.

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
