.TH OCTEZ-SIGNER 1 "January 2024" "Octez Signer Manual"

.SH NAME
octez-signer \- Octez Signer Command Line Interface

.SH SYNOPSIS
.B octez-signer
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B octez-signer
is the command line interface for interacting with the Octez blockchain
to sign blocks while baking.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Octez Documentation: https://tezos.gitlab.io/shell/cli-commands.html
Key Management: https://tezos.gitlab.io/user/key-management.html

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
