{
 "title": "Etherlink governance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Current L1 Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_current_l1_level",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kernel Governance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Configuration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_kernel_configuration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_kernel_remaining_blocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Periode Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_kernel_current_period_type",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Period index",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_kernel_current_period_index",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upgrades",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(etherlink_governance_kernel_trigger_upgrade and changes(etherlink_governance_kernel_trigger_upgrade[$__interval]) > 0) or (etherlink_governance_kernel_trigger_upgrade and ignoring(source,address,job,instance) absent(etherlink_governance_kernel_trigger_upgrade offset $__interval))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "etherlink_governance_kernel_vote",
     "legendFormat": "__auto"
    },
    {
     "expr": "absent(etherlink_governance_kernel_vote offset $__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Voting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_kernel_proposal",
     "legendFormat": "{{proposal}}"
    }
   ]
  },
  {
   "title": "Promotion Voting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etherlink_governance_kernel_vote{value=\"yea\"}) or vector(0)",
     "legendFormat": "« yea »"
    },
    {
     "expr": "sum(etherlink_governance_kernel_vote{value=\"nay\"})  or vector(0)",
     "legendFormat": "« nay »"
    },
    {
     "expr": "sum(etherlink_governance_kernel_vote{value=\"pass\"}) or vector(0)",
     "legendFormat": "« pass »"
    },
    {
     "expr": "sum(etherlink_governance_kernel_vote) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Sequencer Governance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Configuration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_sequencer_configuration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_sequencer_remaining_blocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Periode Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_sequencer_current_period_type",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Period index",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_sequencer_current_period_index",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upgrades",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "(etherlink_governance_sequencer_trigger_commitee_upgrade and changes(etherlink_governance_sequencer_trigger_commitee_upgrade[$__interval]) > 0) or (etherlink_governance_sequencer_trigger_commitee_upgrade and ignoring(source,address,job,instance) absent(etherlink_governance_sequencer_trigger_commitee_upgrade offset $__interval))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "etherlink_governance_sequencer_vote",
     "legendFormat": "__auto"
    },
    {
     "expr": "absent(etherlink_governance_sequencer_vote offset $__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Voting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_sequencer_proposal",
     "legendFormat": "{{proposal}}"
    }
   ]
  },
  {
   "title": "Promotion Voting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etherlink_governance_sequencer_vote{value=\"yea\"}) or vector(0)",
     "legendFormat": "« yea »"
    },
    {
     "expr": "sum(etherlink_governance_sequencer_vote{value=\"nay\"})  or vector(0)",
     "legendFormat": "« nay »"
    },
    {
     "expr": "sum(etherlink_governance_sequencer_vote{value=\"pass\"}) or vector(0)",
     "legendFormat": "« pass »"
    },
    {
     "expr": "sum(etherlink_governance_sequencer_vote) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Security Kernel Governance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Configuration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_security_kernel_configuration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_security_kernel_remaining_blocks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Periode Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_security_kernel_current_period_type",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Period index",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_security_kernel_current_period_index",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upgrades",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "(etherlink_governance_security_kernel_trigger_upgrade and changes(etherlink_governance_security_kernel_trigger_upgrade[$__interval]) > 0) or (etherlink_governance_security_kernel_trigger_upgrade and ignoring(source,address,job,instance) absent(etherlink_governance_security_kernel_trigger_upgrade offset $__interval))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "etherlink_governance_security_kernel_vote",
     "legendFormat": "__auto"
    },
    {
     "expr": "absent(etherlink_governance_security_kernel_vote offset $__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Voting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etherlink_governance_security_kernel_proposal",
     "legendFormat": "{{proposal}}"
    }
   ]
  },
  {
   "title": "Promotion Voting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etherlink_governance_security_kernel_vote{value=\"yea\"}) or vector(0)",
     "legendFormat": "« yea »"
    },
    {
     "expr": "sum(etherlink_governance_security_kernel_vote{value=\"nay\"})  or vector(0)",
     "legendFormat": "« nay »"
    },
    {
     "expr": "sum(etherlink_governance_security_kernel_vote{value=\"pass\"}) or vector(0)",
     "legendFormat": "« pass »"
    },
    {
     "expr": "sum(etherlink_governance_security_kernel_vote) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}