(*****************************************************************************)
(*                                                                           *)
(* SPDX-License-Identifier: MIT                                              *)
(* Copyright (c) 2026 Nomadic Labs. <contact@nomadic-labs.com>               *)
(*                                                                           *)
(*****************************************************************************)

module CI = Cacio.Shared

(* This constant is meant to replace similar constants that are defined elsewhere,
   in particular the one in [job_docker_authenticated] in [ci/lib_tezos_ci/tezos_ci.ml].
   During the migration to Cacio however, those other instances will continue to exist.

   There is another Docker version being used by [base_images.ml]: 28.5.1.
   We should probably try to use the same version everywhere. *)
let version = "24.0.7"

let job_docker =
  Cacio.parameterize @@ fun contents ->
  Cacio.parameterize @@ fun mode ->
  Cacio.parameterize @@ fun arch ->
  CI.job
    ("oc.docker:" ^ Tezos_ci.Runner.Arch.show_uniform arch)
    ~__POS__
    ~description:
      "Build the Docker image for Octez for the specified architecture, with \
       experimental executables."
    ~stage:Build
    ~only_if_changed:["build.Dockerfile"; "Dockerfile"]
    ~allow_failure:No
    ~retry:
      {
        (* Set retry to 1 because the job is a bit flaky.
           The runner sometimes dies, causing the job to fail with EOF.
           Perhaps surprisingly, this surfaces as a [Script_failure]. *)
        Gitlab_ci.Types.max = 1;
        when_ = [Script_failure; Runner_system_failure];
      }
    ~arch
    ~image:Tezos_ci.Images_external.docker
    ~image_dependencies:
      (match contents with
      | `experimental_with_evm ->
          [Tezos_ci.Images.CI.runtime; Tezos_ci.Images.rust_toolchain]
      | `released | `experimental -> [Tezos_ci.Images.CI.runtime])
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", version);
        ("CI_DOCKER_HUB", match mode with `real -> "true" | `test -> "false");
        ( "DOCKER_BUILD_TARGET",
          match contents with
          | `experimental_with_evm -> "with-evm-artifacts"
          | `released | `experimental -> "without-evm-artifacts" );
        ("IMAGE_ARCH_PREFIX", Tezos_ci.Runner.Arch.show_uniform arch ^ "_");
        ( "EXECUTABLE_FILES",
          match contents with
          | `experimental_with_evm | `experimental ->
              "script-inputs/released-executables \
               script-inputs/experimental-executables"
          | `released -> "script-inputs/released-executables" );
      ]
    ["./scripts/ci/docker_initialize.sh"; "./scripts/ci/docker_release.sh"]

let job_docker_merge_manifests =
  Cacio.parameterize @@ fun contents ->
  Cacio.parameterize @@ fun mode ->
  CI.job
    "docker:merge_manifests"
    ~__POS__
    ~description:
      "Merge the Docker images generated by jobs oc.docker:{amd64,arm64} into \
       a single multi-architecture image."
    ~stage:Publish
    ~retry:Gitlab_ci.Types.{max = 0; when_ = []}
    ~image:Tezos_ci.Images_external.docker
    ~needs:
      [
        (Job, job_docker contents mode Amd64);
        ( Job,
          job_docker
            (match contents with
            | `experimental_with_evm ->
                (* No EVM node on arm64. *) `experimental
            | `experimental | `released -> contents)
            mode
            Arm64 );
      ]
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", version);
        ("CI_DOCKER_HUB", match mode with `real -> "true" | `test -> "false");
      ]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_merge_manifests.sh";
    ]

let job_script_docker_verify_image =
  Cacio.parameterize @@ fun arch ->
  let arch_string = Tezos_ci.Runner.Arch.show_uniform arch in
  CI.job
    ("oc.script.docker_verify_image_" ^ arch_string)
    ~__POS__
    ~description:"Verify the signature of the Docker image."
    ~stage:Test
    ~only_if_changed:
      [
        "build.Dockerfile";
        "Dockerfile";
        (* Scripts that are directly called by this job. *)
        "scripts/ci/docker_initialize.sh";
        "scripts/ci/docker_verify_signature.sh";
        (* Scripts that are called by [docker_initialize.sh]. *)
        "scripts/ci/docker_wait_for_daemon.sh";
        "scripts/ci/docker_check_version.sh";
        "scripts/ci/docker_registry_auth.sh";
        (* Scripts that are called by [docker_registry_auth.sh]. *)
        "scripts/ci/docker_image_names.sh";
        (* Scripts that are called by [docker_image_names.sh]. *)
        "scripts/ci/docker_registry.inc.sh";
        (* Scripts that are called by the Docker build jobs that this job depends on. *)
        "scripts/ci/docker_release.sh";
        (* Scripts that are called by [docker_release.sh]. *)
        "scripts/create_docker_image.sh";
        "scripts/ci/docker_smoke_test.sh";
        "scripts/ci/docker_push_all.sh";
        "scripts/ci/docker_sign.sh";
        (* TODO: since the Docker build jobs already call [docker_verify_signature.sh],
           why have a job dedicated to running [docker_verify_signature.sh]? *)
        "scripts/ci/docker_verify_signature.sh";
        (* Scripts that are called by [create_docker_image.sh]. *)
        "scripts/version.sh";
      ]
    ~needs:
      [
        ( Job,
          job_docker
            (match arch with
            | Amd64 -> `experimental_with_evm
            | Arm64 -> `experimental)
            `test
            arch );
      ]
    ~image:Tezos_ci.Images_external.docker
    ~variables:
      [("DOCKER_VERSION", version); ("IMAGE_ARCH_PREFIX", arch_string ^ "_")]
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_verify_signature.sh";
    ]

let register () =
  Cacio.register_jobs
    Before_merging
    [
      (Auto, job_docker `experimental_with_evm `test Amd64);
      (Auto, job_docker `experimental `test Arm64);
      (Manual, job_script_docker_verify_image Amd64);
      (Manual, job_script_docker_verify_image Arm64);
    ] ;
  Cacio.register_jobs
    Merge_train
    [
      (Auto, job_docker `experimental_with_evm `test Amd64);
      (Auto, job_docker `experimental `test Arm64);
    ] ;
  Cacio.register_jobs
    Master
    [(Auto, job_docker_merge_manifests `experimental_with_evm `real)] ;
  Cacio.register_jobs
    Scheduled_docker_build
    [(Auto, job_docker_merge_manifests `experimental_with_evm `real)] ;
  ()
