(*****************************************************************************)
(*                                                                           *)
(* SPDX-License-Identifier: MIT                                              *)
(* Copyright (c) 2026 Nomadic Labs. <contact@nomadic-labs.com>               *)
(*                                                                           *)
(*****************************************************************************)

module CI = Cacio.Shared

let job_docker =
  Cacio.parameterize @@ fun arch ->
  Cacio.parameterize @@ fun contents ->
  CI.job
    ("oc.docker:" ^ Tezos_ci.Runner.Arch.show_uniform arch)
    ~__POS__
    ~description:
      "Build the Docker image for Octez for the specified architecture, with \
       experimental executables."
    ~stage:Build
    ~allow_failure:No
    ~retry:
      {
        (* Set retry to 1 because the job is a bit flaky.
           The runner sometimes dies, causing the job to fail with EOF.
           Perhaps surprisingly, this surfaces as a [Script_failure]. *)
        Gitlab_ci.Types.max = 1;
        when_ = [Script_failure; Runner_system_failure];
      }
    ~arch
    ~image:Tezos_ci.Images_external.docker
    ~image_dependencies:
      (match contents with
      | `with_evm ->
          [Tezos_ci.Images.CI.runtime; Tezos_ci.Images.rust_toolchain]
      | `without_evm -> [Tezos_ci.Images.CI.runtime])
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", Release_tag.docker_version);
        ("CI_DOCKER_HUB", "true");
        ( "DOCKER_BUILD_TARGET",
          match contents with
          | `with_evm -> "with-evm-artifacts"
          | `without_evm -> "without-evm-artifacts" );
        ("IMAGE_ARCH_PREFIX", Tezos_ci.Runner.Arch.show_uniform arch ^ "_");
        ( "EXECUTABLE_FILES",
          "script-inputs/released-executables \
           script-inputs/experimental-executables" );
      ]
    ["./scripts/ci/docker_initialize.sh"; "./scripts/ci/docker_release.sh"]

let job_docker_merge_manifests =
  CI.job
    "docker:merge_manifests"
    ~__POS__
    ~description:
      "Merge the Docker images generated by jobs oc.docker:{amd64,arm64} into \
       a single multi-architecture image."
    ~stage:Publish
    ~retry:Gitlab_ci.Types.{max = 0; when_ = []}
    ~image:Tezos_ci.Images_external.docker
    ~needs:
      [(Job, job_docker Amd64 `with_evm); (Job, job_docker Arm64 `without_evm)]
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", Release_tag.docker_version); ("CI_DOCKER_HUB", "true");
      ]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_merge_manifests.sh";
    ]

let register () =
  Cacio.register_jobs Master [(Auto, job_docker_merge_manifests)] ;
  Cacio.register_jobs
    Scheduled_docker_build
    [(Auto, job_docker_merge_manifests)] ;
  ()
