(*****************************************************************************)
(*                                                                           *)
(* SPDX-License-Identifier: MIT                                              *)
(* Copyright (c) 2024 Nomadic Labs. <contact@nomadic-labs.com>               *)
(*                                                                           *)
(*****************************************************************************)

(* This module defines the jobs of the [master_branch] pipeline.

   This pipeline runs for each merge on the [master] branch. To goal
   of this pipeline is to publish artifacts for the latest development
   version of Octez (e.g. the latest version on 'master'), including:

   - docker images,
   - static binaries, and
   - documentation. *)

open Common.Docker
open Gitlab_ci.Util
open Tezos_ci
module CI = Cacio.Shared

let rules_always = [job_rule ~when_:Always ()]

let job_docker_amd64_experimental : tezos_job =
  job_docker_build ~__POS__ ~rules:rules_always ~arch:Amd64 Experimental

let job_docker_arm64_experimental : tezos_job =
  job_docker_build
    ~__POS__
    ~rules:rules_always
    ~arch:Arm64
    ~storage:Ramfs
    Experimental

let job_docker_merge_manifests =
  CI.job
    "docker:merge_manifests"
    ~__POS__
    ~description:
      "Merge the Docker images generated by jobs oc.docker:{amd64,arm64} into \
       a single multi-architecture image."
    ~stage:Publish
    ~retry:Gitlab_ci.Types.{max = 0; when_ = []}
    ~image:Images_external.docker
    ~needs_legacy:
      [
        (Job, job_docker_amd64_experimental);
        (Job, job_docker_arm64_experimental);
      ]
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", Release_tag.docker_version); ("CI_DOCKER_HUB", "true");
      ]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_merge_manifests.sh";
    ]

let () =
  Cacio.register_jobs Master [(Auto, job_docker_merge_manifests)] ;
  Cacio.register_jobs
    Scheduled_docker_build
    [(Auto, job_docker_merge_manifests)] ;
  ()

let octez_distribution_docker_jobs =
  [
    (* Stage: build *)
    job_docker_amd64_experimental;
    job_docker_arm64_experimental;
  ]

(* Defines the jobs of the [schedule_docker_build_pipeline] pipeline.

    This pipeline runs scheduled on the [master] branch. The goal
   of this pipeline is to publish fresh Docker images for 'master' using the latest Alpine packages. *)

let jobs =
  (* Like in the {!Schedule_extended_test} variant of
     {!Code_verification} pipelines, we'd like to run as many jobs as
     possible in [master_branch] pipelines. Therefore, the default
     [when_] should be [Always] for jobs without dependencies.

     [changes:] clauses can be used on [master_branch] pipelines. In
     push pipelines like this one, [changes:]-clauses match against
     the diff of the branch's [HEAD] between two pushes. That is, the
     the difference between the previous state and the new state of
     the branch. In the case of the [master] branch, this is just the
     contents of the most recently merged MR. For more info on
     [changes:] in different pipelines, see
     {{:https://docs.gitlab.com/ee/ci/jobs/job_troubleshooting.html#jobs-or-pipelines-run-unexpectedly-when-using-changes}
     GitLab Docs: Jobs or pipelines run unexpectedly when using changes}. *)
  [(* Stage: sanity *) job_datadog_pipeline_trace]
  (* Jobs to build and update on Docker Hub the Octez Docker image.  *)
  @ octez_distribution_docker_jobs
