(*****************************************************************************)
(*                                                                           *)
(* SPDX-License-Identifier: MIT                                              *)
(* Copyright (c) 2024 Nomadic Labs. <contact@nomadic-labs.com>               *)
(*                                                                           *)
(*****************************************************************************)

(* This module defines the jobs of the [release_tag] family of pipelines.

   These pipeline runs on each pushes to the various release tags (see
   [main.ml] for the set of regular expressions that define the
   language of release tags).

   The goal of these pipelines is to create
   {{:https://gitlab.com/tezos/tezos/-/releases}Octez releases on
   GitLab}, the associated artifacts, and to push releases to opam. *)

open Tezos_ci
open Common.Docker

(* Some jobs have been migrated to Cacio, in the shared component. *)
module CI = Cacio.Shared

(* Release jobs must not be retried: they publish artifacts and retrying could
   result in publishing the same artifact twice. *)
let no_retry = Gitlab_ci.Types.{max = 0; when_ = []}

let monitoring_child_pipeline =
  (* Using lazy lets us define the pipeline at toplevel,
     but actually execute the code after the jobs have been defined with Cacio
     (they have not yet been defined when this toplevel definition is executed),
     and only once (there are multiple pipelines with a trigger job for octez_monitoring,
     but a pipeline cannot be registered more than once). *)
  lazy
    (Pipeline.register_child
       "octez_monitoring"
       ~description:"Octez monitoring jobs"
       ~inherit_:
         (Gitlab_ci.Types.Variable_list
            ["ci_image_name"; "ci_image_name_protected"; "jsonnet_image_name"])
       ~jobs:([job_datadog_pipeline_trace] @ Cacio.get_jobs Octez_monitoring))

let docker_version = "24.0.7"

let job_docker =
  Cacio.parameterize @@ fun mode ->
  Cacio.parameterize @@ fun trigger ->
  Cacio.parameterize @@ fun arch ->
  job_docker_build
    ~__POS__
    ~dependencies:(Dependent [])
    ?rules:
      (match trigger with
      | `manual ->
          Some [Gitlab_ci.Util.job_rule ~when_:Manual ~allow_failure:No ()]
      | `auto -> None)
    ~arch
    ?storage:(match arch with Arm64 -> Some Ramfs | _ -> None)
    (match mode with `test -> Test | `real -> Release)

let job_docker_merge =
  Cacio.parameterize @@ fun mode ->
  Cacio.parameterize @@ fun trigger ->
  CI.job
    "docker:merge_manifests"
    ~__POS__
    ~description:
      "Merge the Docker images generated by jobs oc.docker:{amd64,arm64} into \
       a single multi-architecture image."
    ~stage:Publish
    ~retry:Gitlab_ci.Types.{max = 0; when_ = []}
    ~image:Images_external.docker
    ~needs_legacy:
      [
        (Job, job_docker mode trigger Amd64);
        (Job, job_docker mode trigger Arm64);
      ]
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", docker_version);
        ("CI_DOCKER_HUB", match mode with `test -> "false" | `real -> "true");
      ]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_merge_manifests.sh";
    ]

(* This job normally runs in the {!Octez_latest_release} pipeline
   that is triggered manually after a release is made.
   However, to make release testing easier, we include it in other test release pipelines.
   Thus, release testers are not required to trigger two separate pipelines
   (indeed, the second [latest_release_test] pipeline is rarely tested).
   This version of the job is only for testing (mode [`test]);
   the [`real] version is in [octez_latest_release.ml]. *)
let job_docker_promote_to_latest =
  Cacio.parameterize @@ fun mode ->
  CI.job
    "docker:promote_to_latest"
    ~__POS__
    ~description:"Add the latest tag to the new Docker images."
    ~image:Images_external.docker
    ~stage:Publish
    ~needs:
      (match mode with
      | `test_wait ->
          (* In pipelines other than latest release pipelines,
             we want to wait for the Docker image to exist. *)
          [(Job, job_docker_merge `test `auto)]
      | `test | `real ->
          (* In latest release pipelines, the Docker image already exists,
             as it was created by another pipeline (the tag pipeline). *)
          [])
    ~retry:Gitlab_ci.Types.{max = 0; when_ = []}
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", docker_version);
        ( "CI_DOCKER_HUB",
          match mode with `test | `test_wait -> "false" | `real -> "true" );
      ]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_promote_to_latest.sh";
    ]

let job_build_homebrew_release =
  add_artifacts
    ~name:"build-$CI_COMMIT_REF_SLUG"
    ~expire_in:(Duration (Days 1))
    ~when_:On_success
    ["public/homebrew/*"]
    Homebrew.job_create_homebrew_formula

let job_gitlab_release =
  Cacio.parameterize @@ fun mode ->
  CI.job
    "gitlab:release"
    ~__POS__
    ~description:"Create a GitLab release."
    ~image:Images.Base_images.ci_release
    ~stage:Publish
    ~needs:
      [
        (Artifacts, Build.job_build_static_linux_binaries Amd64 `release);
        (Artifacts, Build.job_build_static_linux_binaries Arm64 `release);
        (Job, job_docker_merge mode `auto);
      ]
    ~needs_legacy:[(Artifacts, job_build_homebrew_release)]
    ~id_tokens:Tezos_ci.id_tokens
    [
      "./scripts/ci/restrict_export_to_octez_source.sh";
      "./scripts/releases/gitlab-release.sh";
    ]

let job_gitlab_publish =
  Cacio.parameterize @@ fun mode ->
  CI.job
    "gitlab:publish"
    ~__POS__
    ~description:"Create a GitLab package."
    ~image:Images.Base_images.ci_release
    ~stage:Publish
    ~needs:
      [
        (Artifacts, Build.job_build_static_linux_binaries Amd64 `release);
        (Artifacts, Build.job_build_static_linux_binaries Arm64 `release);
      ]
    ~needs_legacy:[(Artifacts, job_build_homebrew_release)]
    ?variables:
      (match mode with
      | `scheduled_test -> Some [("CI_COMMIT_TAG", "octez-v0.0")]
      | `non_release_tag -> None)
    ~id_tokens:Tezos_ci.id_tokens
    ((match mode with
     | `scheduled_test -> ["git tag octez-v0.0"]
     | `non_release_tag -> [])
    @ [
        ("${CI_PROJECT_DIR}/scripts/ci/create_gitlab_package.sh"
        ^
        match mode with
        | `scheduled_test -> " --dry-run"
        | `non_release_tag -> "");
      ])

let job_release_page =
  Cacio.parameterize @@ fun mode ->
  Cacio.parameterize @@ fun wait_for ->
  CI.job
    "publish:release-page"
    ~__POS__
    ~image:Images.CI.release_page
    ~stage:Publish
    ~description:
      "A job to update the Octez release page. If running in a test pipleine, \
       the assets are pushed in the [release-page-test.nomadic-labs.com] \
       bucket. Otherwise they are pushed in [site.prod.octez.tezos.com]. Then \
       its [index.html] is updated accordingly."
    ~artifacts:
      (Gitlab_ci.Util.artifacts
         ~expire_in:(Duration (Days 1))
         ["./index.md"; "index.html"])
    ?needs:
      (match wait_for with
      | `wait_for_nothing -> None
      | `wait_for_build ->
          Some
            [
              (Artifacts, Build.job_build_static_linux_binaries Amd64 `release);
              (Artifacts, Build.job_build_static_linux_binaries Arm64 `release);
            ])
    ~variables:
      (match mode with
      | `test ->
          (* The S3_BUCKET, AWS keys and DISTRIBUTION_ID
            depends on the release type (tests or not). *)
          [
            ("S3_BUCKET", "release-page-test.nomadic-labs.com");
            ("DISTRIBUTION_ID", "E19JF46UG3Z747");
            ("AWS_ACCESS_KEY_ID", "${AWS_KEY_RELEASE_PUBLISH}");
            ("AWS_SECRET_ACCESS_KEY", "${AWS_SECRET_RELEASE_PUBLISH}");
          ]
      | `real ->
          [
            ("S3_BUCKET", "site-prod.octez.tezos.com");
            ("BUCKET_PATH", "/releases");
            ("URL", "octez.tezos.com");
            ("DISTRIBUTION_ID", "${CLOUDFRONT_DISTRIBUTION_ID}");
          ])
    [
      "eval $(opam env)";
      "./scripts/releases/publish_release_page.sh";
      "cp /tmp/release_page*/index.md ./index.md";
    ]

let job_opam_release =
  Cacio.parameterize @@ fun mode ->
  CI.job
    "opam:release"
    ~__POS__
    ~image:Images.CI.prebuild
    ~stage:Publish
    ~description:
      "Update opam package descriptions on tezos/tezos opam-repository fork.\n\n\
       This job does preliminary work for releasing Octez opam packages on \
       opam repository, by pushing a branch with updated package descriptions \
       (.opam files) to https://github.com/tezos/opam-repository. It _does \
       not_ automatically create a corresponding pull request on the official \
       opam repository."
    [
      ("./scripts/ci/opam-release.sh"
      ^ match mode with `test -> " --dry-run" | `real -> "");
    ]

let job_dispatch_call =
  CI.job
    "dispatch-call"
    ~__POS__
    ~image:Images.CI.prebuild
    ~stage:Publish
    ~description:
      "A job release that triggers pipelines from other repositories after a \
       release.\n\
       For now, it triggers the release pipeline from \
       tez-capital/tezos-macos-pipeline"
    ~needs:
      [
        (Job, job_gitlab_release `real);
        (Job, job_release_page `real `wait_for_build);
      ]
    ["./scripts/releases/dispatch-call.sh"]

let () =
  (* Major *)
  Cacio.register_jobs
    Major_release_tag
    [
      (Auto, job_docker_merge `real `auto);
      (Auto, job_gitlab_release `real);
      (Manual, job_release_page `real `wait_for_build);
      (Auto, job_opam_release `real);
      (Auto, job_dispatch_call);
    ] ;
  Cacio.register_jobs
    Major_release_tag_test
    [
      (Auto, job_docker_merge `test `auto);
      (Auto, job_gitlab_release `test);
      (Manual, job_release_page `test `wait_for_build);
      (Auto, job_opam_release `test);
      (Auto, job_docker_promote_to_latest `test_wait);
    ] ;
  (* Minor *)
  Cacio.register_jobs
    Minor_release_tag
    [
      (Auto, job_docker_merge `real `auto);
      (Auto, job_gitlab_release `real);
      (Manual, job_release_page `real `wait_for_build);
      (Auto, job_opam_release `real);
      (Auto, job_dispatch_call);
    ] ;
  Cacio.register_jobs
    Minor_release_tag_test
    [
      (Auto, job_docker_merge `test `auto);
      (Auto, job_gitlab_release `test);
      (Manual, job_release_page `test `wait_for_build);
      (Auto, job_opam_release `test);
      (Auto, job_docker_promote_to_latest `test_wait);
    ] ;
  (* Beta *)
  Cacio.register_jobs
    Beta_release_tag
    [
      (Auto, job_docker_merge `real `auto);
      (Auto, job_gitlab_release `real);
      (Manual, job_release_page `real `wait_for_build);
      (Auto, job_dispatch_call);
    ] ;
  Cacio.register_jobs
    Beta_release_tag_test
    [
      (Auto, job_docker_merge `test `auto);
      (Auto, job_gitlab_release `test);
      (Manual, job_release_page `test `wait_for_build);
    ] ;
  (* Non-release *)
  Cacio.register_jobs
    Non_release_tag
    [
      (Auto, job_docker_merge `real `auto);
      (Auto, job_gitlab_publish `non_release_tag);
    ] ;
  Cacio.register_jobs
    Non_release_tag_test
    [
      (Auto, job_docker_merge `test `auto);
      (Auto, job_gitlab_publish `non_release_tag);
    ] ;
  (* Scheduled *)
  Cacio.register_jobs
    Scheduled_test_release
    [
      (Auto, job_docker_merge `test `auto);
      (Auto, job_gitlab_publish `scheduled_test);
    ] ;
  (* Release page *)
  Cacio.register_jobs
    Publish_release_page
    [(Manual, job_release_page `real `wait_for_nothing)] ;
  Cacio.register_jobs
    Test_publish_release_page
    [(Manual, job_release_page `test `wait_for_nothing)] ;
  (* Octez Latest Release *)
  Cacio.register_jobs
    Octez_latest_release
    [(Auto, job_docker_promote_to_latest `real)] ;
  Cacio.register_jobs
    Octez_latest_release_test
    [(Auto, job_docker_promote_to_latest `test)] ;
  ()

(** Create an Octez release tag pipeline of type {!pipeline_type},
    which is expected to be a release pipeline type. *)
let octez_jobs (pipeline_type : Cacio.global_pipeline) =
  let mode =
    match pipeline_type with
    | Major_release_tag | Minor_release_tag | Beta_release_tag | Non_release_tag
      ->
        `real
    | _ -> `test
  in
  let jobs_debian_repository =
    Debian_repository.jobs ~limit_dune_build_jobs:true Release
  in
  let job_trigger_monitoring =
    trigger_job
      ~__POS__
      ~dependencies:(Dependent [])
      ~stage:Stages.build
      (Lazy.force monitoring_child_pipeline)
  in
  [
    (* Stage: start *)
    job_datadog_pipeline_trace;
    (* Stage: build *)
    job_docker mode `auto Amd64;
    job_docker mode `auto Arm64;
    job_build_homebrew_release;
  ]
  @ [job_trigger_monitoring] @ jobs_debian_repository
  @ Cacio.get_jobs pipeline_type

let job_docker_promote_to_version =
  Cacio.parameterize @@ fun mode ->
  CI.job
    "oc.docker:promote_revision_to_version"
    ~__POS__
    ~description:
      "Promote the Docker image from the packaging revision tag to the \
       canonical version tag (e.g., octez-v1.2 from octez-v1.2-1)"
    ~image:Images_external.docker
    ~stage:Publish
    ~allow_failure:No
    ~needs:[(Job, job_docker_merge mode `manual)]
    ~retry:Gitlab_ci.Types.{max = 0; when_ = []}
    ~services:[{name = "docker:${DOCKER_VERSION}-dind"}]
    ~variables:
      [
        ("DOCKER_VERSION", docker_version);
        ("CI_DOCKER_HUB", match mode with `test -> "false" | `real -> "true");
      ]
    [
      "./scripts/ci/docker_initialize.sh";
      "./scripts/ci/docker_promote_to_version.sh";
    ]

let job_create_gitlab_package =
  CI.job
    "gitlab:create_package"
    ~__POS__
    ~image:Images.Base_images.ci_release
    ~stage:Publish
    ~description:
      "Create GitLab packages with static binaries from this packaging revision"
    ~needs:
      [
        (Artifacts, Build.job_build_static_linux_binaries Amd64 `release);
        (Artifacts, Build.job_build_static_linux_binaries Arm64 `release);
      ]
    ~id_tokens:Tezos_ci.id_tokens
    ~allow_failure:No
    ["./scripts/ci/create_gitlab_package.sh"]
    ~retry:no_retry
    ~tag:Gcp_not_interruptible

let job_update_gitlab_release =
  CI.job
    "gitlab:update_release"
    ~__POS__
    ~image:Images.Base_images.ci_release
    ~stage:Publish
    ~description:
      "Update existing GitLab release with new static binaries from this \
       packaging revision"
    ~needs:[(Job, job_create_gitlab_package)]
    ~id_tokens:Tezos_ci.id_tokens
    ["./scripts/releases/update_gitlab_release.sh"]
    ~retry:no_retry
    ~tag:Gcp_not_interruptible

let () =
  Cacio.register_jobs
    Packaging_revision
    [
      (Manual, job_create_gitlab_package);
      (Auto, job_update_gitlab_release);
      (* [`manual] because the docker build jobs should be manual.
         This will go away after the docker build jobs are migrated to Cacio. *)
      (Auto, job_docker_merge `real `manual);
      (Manual, job_docker_promote_to_version `real);
    ] ;
  Cacio.register_jobs
    Packaging_revision_test
    [
      (Manual, job_create_gitlab_package);
      (Auto, job_update_gitlab_release);
      (Auto, job_docker_merge `test `manual);
      (Manual, job_docker_promote_to_version `test);
    ] ;
  ()

let octez_packaging_revision_jobs ?(test = false) () =
  let mode = if test then `test else `real in
  let jobs_debian_repository =
    Debian_repository.jobs ~limit_dune_build_jobs:true ~manual:true Release
  in
  (* We want to be able to trigger each "batch" of jobs manually.
     There are two batches: one with the static jobs, and one that publishes.
     The static jobs are independent so they are both manual,
     but [job_update_gitlab_release] depends on [job_create_gitlab_package]
     so it does not have to be manual, only [job_create_gitlab_package] does. *)
  [
    (* Stage: start *)
    job_datadog_pipeline_trace;
    (* Docker images *)
    job_docker mode `manual Amd64;
    job_docker mode `manual Arm64;
  ]
  @ jobs_debian_repository
  @
  if test then Cacio.get_jobs Packaging_revision_test
  else Cacio.get_jobs Packaging_revision
