/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.tezos.add

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    println("1 + 2 = ${add(1u, 2u)}")
}
