#!/bin/bash

# this scripts call scripts/packaging/tests/systemd-docker-test.sh on the CI.
# We first install the needed alpine packages
# The $TESTFILE is a scripts the is going to be executed in the container
# generated by the docker image specified in as $DOCKERFILE
# Check the script scripts/packaging/tests/systemd-docker-test.sh for more
# details.

TESTFILE=${1:?You must specify a test file to run}
DOCKERFILE=${2:?You must specify a dockerfile}

set -eu

apk --no-cache add screen procps bash

scripts/packaging/tests/systemd-docker-test.sh "$TESTFILE" "$DOCKERFILE"
