# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-integration-tests"
publish = false
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
url.workspace = true
hyper.workspace = true
hex.workspace = true
tokio.workspace = true
tokio-util.workspace = true
ethers.workspace = true
jsonrpc-http-server.workspace = true
env_logger.workspace = true
clap.workspace = true
reqwest.workspace = true
dsn-core.workspace = true
chrono.workspace = true
serde_json.workspace = true
futures.workspace = true
futures-util.workspace = true
jsonrpsee-http-client.workspace = true
jsonrpsee-core.workspace = true

[[bin]]
name = "jsonrpc-mock"
path = "src/jsonrpc_mock.rs"

[[test]]
name = "bundler"
path = "bundler_tests.rs"

[[test]]
name = "sequencer"
path = "sequencer_tests.rs"
