[package]
name = "tezos_data_encoding_derive"
version = "0.6.0"
authors = ["TriliTech <contact@trili.tech>"]
edition = "2021"
rust-version = "1.64"
license = "MIT"
keywords = ["tezos"]
categories = ["encoding"]
description = "Procedural macros for tezos_encoding."
repository = "https://github.com/trilitech/tezedge.git"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"]}
quote = "1.0"
lazy_static = "1.4.0"
parse-display = "0.4.1"
once_cell = "1.9.0"

[features]
fuzzing = []
