{
 "title": "Rollup Node",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": {
     "query": "label_values(octez_sc_rollup_node_rollup_node_info,instance)"
    }
   },
   {
    "name": "injectors",
    "query": {
     "query": "label_values({instance=\"$node_instance\"},__name__)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Protocol information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_protocol{instance=\"$node_instance\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Constants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_commitment_period{instance=\"$node_instance\"}",
     "legendFormat": "Commitment period"
    },
    {
     "expr": "octez_sc_rollup_node_challenge_window{instance=\"$node_instance\"}",
     "legendFormat": "Challenge window"
    },
    {
     "expr": "octez_sc_rollup_node_dal_enabled{instance=\"$node_instance\"}",
     "legendFormat": "DAL enabled"
    },
    {
     "expr": "octez_sc_rollup_node_dal_attestation_lag{instance=\"$node_instance\"}",
     "legendFormat": "DAL attestation lag"
    },
    {
     "expr": "octez_sc_rollup_node_dal_number_of_slots{instance=\"$node_instance\"}",
     "legendFormat": "DAL #slots"
    }
   ]
  },
  { "title": "Generic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rollup Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_rollup_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Rollup Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_rollup_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ rollup_address }}"
    }
   ]
  },
  {
   "title": "Genesis Hash",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_rollup_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ genesis_hash }}"
    }
   ]
  },
  {
   "title": "PVM Kind",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_rollup_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ pvm_kind }}"
    }
   ]
  },
  {
   "title": "History mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_rollup_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ history_mode }}"
    }
   ]
  },
  {
   "title": "Genesis Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_rollup_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ genesis_level }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_node_info{instance=\"$node_instance\"}",
     "legendFormat": "{{ commit_date }}"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(label_replace(octez_sc_rollup_node_node_info{instance=\"$node_instance\"},\"commit_hash_short\" ,\"$1\",\"commit_hash\",\"^(.{8}).*$\"))",
     "legendFormat": "{{ commit_hash_short }}"
    }
   ]
  },
  { "title": "Levels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rollup node head",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_inbox_level{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Cementation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_lcc_level_l1{instance=\"$node_instance\"}",
     "legendFormat": "LCC level"
    },
    {
     "expression": "floor(($lpc - $lcc - $window) / $period)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Commitments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_lpc_level_l1{instance=\"$node_instance\"}",
     "legendFormat": "Last published level"
    },
    { "expression": "$head - $lpc", "type": "math" },
    { "expression": "$period - $head + $lpc", "type": "math" }
   ]
  },
  {
   "title": "Local LCC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_lcc_level_local{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Local LPC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_lpc_level_local{instance=\"$node_instance\"}"
    }
   ]
  },
  { "title": "Inbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_inbox_internal_messages_number{instance=\"$node_instance\"}",
     "legendFormat": "internal"
    },
    {
     "expr": "octez_sc_rollup_node_inbox_external_messages_number{instance=\"$node_instance\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_inbox_process_time{instance=\"$node_instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "octez_sc_rollup_node_inbox_fetch_time{instance=\"$node_instance\"}",
     "legendFormat": "fetch"
    },
    {
     "expr": "octez_sc_rollup_node_inbox_total_time{instance=\"$node_instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Messages Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_inbox_internal_messages_number{instance=\"$node_instance\"}",
     "legendFormat": "internal"
    },
    {
     "expr": "octez_sc_rollup_node_inbox_external_messages_number{instance=\"$node_instance\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Processing Time Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_inbox_process_time{instance=\"$node_instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "octez_sc_rollup_node_inbox_fetch_time{instance=\"$node_instance\"}",
     "legendFormat": "fetch"
    },
    {
     "expr": "octez_sc_rollup_node_inbox_total_time{instance=\"$node_instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Batcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Batcher Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_batcher_get_time{instance=\"$node_instance\"}",
     "legendFormat": "fetch"
    },
    {
     "expr": "octez_sc_rollup_node_batcher_inject_time{instance=\"$node_instance\"}",
     "legendFormat": "inject"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Batcher Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_batcher_message_queue_size{instance=\"$node_instance\"}",
     "legendFormat": "queue"
    },
    {
     "expr": "octez_sc_rollup_node_batcher_messages_size{instance=\"$node_instance\"}",
     "legendFormat": "messages"
    },
    {
     "expr": "octez_sc_rollup_node_batcher_batches_size{instance=\"$node_instance\"}",
     "legendFormat": "batches"
    }
   ]
  },
  {
   "title": "Last Batch Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_batcher_last_batch_level{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Last Batch Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_batcher_last_batch_time{instance=\"$node_instance\"}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Oldest Available Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_gc_oldest_available_level{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "GC Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_gc_process_time{instance=\"$node_instance\"}"
    }
   ]
  },
  { "title": "Injector $injectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }, "repeat": "injectors" },
  {
   "title": "Injector $injectors operations",
   "type": "stat",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "octez_injector_${injectors}_tags{instance=\"$node_instance\"}",
     "legendFormat": "{{tags}}"
    }
   ]
  },
  {
   "title": "Injector ${injectors}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "octez_injector_${injectors}_queue_size{instance=\"$node_instance\"}",
     "legendFormat": "queue"
    },
    {
     "expr": "octez_injector_${injectors}_injected_size{instance=\"$node_instance\"}",
     "legendFormat": "injected"
    },
    {
     "expr": "octez_injector_${injectors}_included_size{instance=\"$node_instance\"}",
     "legendFormat": "included"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Go" } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_performance_virtual{instance=\"$node_instance\"}",
     "legendFormat": "virtual"
    },
    {
     "expr": "octez_sc_rollup_node_performance_resident{instance=\"$node_instance\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "Percentages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_performance_cpu_percentage{instance=\"$node_instance\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "octez_sc_rollup_node_performance_mem_percentage{instance=\"$node_instance\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Go" } },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_performance_data{instance=\"$node_instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "octez_sc_rollup_node_performance_storage{instance=\"$node_instance\"}",
     "legendFormat": "storage"
    },
    {
     "expr": "octez_sc_rollup_node_performance_context{instance=\"$node_instance\"}",
     "legendFormat": "context"
    },
    {
     "expr": "octez_sc_rollup_node_performance_logs{instance=\"$node_instance\"}",
     "legendFormat": "logs"
    },
    {
     "expr": "octez_sc_rollup_node_performance_wasm{instance=\"$node_instance\"}",
     "legendFormat": "preimages"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "octez_sc_rollup_node_performance_file_descriptors{instance=\"$node_instance\"}",
     "legendFormat": "file descr"
    },
    {
     "expr": "octez_sc_rollup_node_performance_connections{instance=\"$node_instance\"}",
     "legendFormat": "connections"
    }
   ]
  }
 ]
}