variable "project_url" {
  type        = string
  description = "GitLab - The HTTPS address of the project"
  default     = "https://gitlab.com/trili/wasm-demo"
}

variable "project_id" {
  type        = string
  description = "The GCP project ID"
  default     = "nl-dal"
}

variable "region" {
  type        = string
  description = "The GCP region where the unmanaged instance group resides."
  default     = "europe-west1"
}

variable "zone" {
  type        = string
  description = "Set this variable to force a particular zone within the region"
  default     = "europe-west1-c"
}

variable "hostname" {
  type        = string
  description = "Hostname prefix for instances."
  default     = "lin"
}

variable "target_size" {
  type        = string
  description = "The target number of running instances for this managed or unmanaged instance group. This value should always be explicitly set unless this resource is attached to an autoscaler, in which case it should never be set."
  default     = 1
}

variable "docker_registry_url" {
  type        = string
  description = "Google docker image registry (artifact registry) URL to authenticate with"
  default     = "europe-docker.pkg.dev"
}

variable "gcp_creds" {
  type        = string
  description = "Credentials for GCP provider (GOOGLE_CREDENTIALS) if not already provided"
  default     = ""
}

# Parameters for monitoring

variable "prom_graf_user" {
  type        = string
  description = "Prometheus & Grafana main user password (default = 'admin')"
  sensitive   = true
  default     = "admin"
}

variable "prom_graf_password" {
  type        = string
  default     = ""
  description = "Prometheus & Grafana main password (can be empty, will be autogenerated)"
  sensitive   = true
}
