# SPDX-FileCopyrightText: 2022-2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-macros"
version = "0.2.2"
edition = "2021"
license = "MIT"
authors = ["TriliTech <contact@trili.tech>"]
repository = "https://gitlab.com/tezos/tezos.git"
description = "Procedural macros for Tezos Smart Rollup kernels."
keywords = ["tezos", "smart", "rollup"]

[lib]
proc-macro = true

[features]
default = ["runtime-options", "entrypoint"]
native-kernel = []
runtime-options = []
entrypoint = []

[dependencies]
proc-macro-error2 = "2.0.1"
quote = "1.0.36"

[dependencies.syn]
version = "2.0.65"
features = ["full"]

[dependencies.shellexpand]
version = "3.1.0"

[dependencies.tezos-smart-rollup-build-utils]
path = "../build-utils"
features = ["macro-support"]

[dev-dependencies.tezos-smart-rollup]
version = "0.2.2"
path = "../sdk"
features = [
	"std",
	"crypto",
	"panic-hook",
	"data-encoding",
	"proto-alpha",
	"experimental-host-in-memory-store",
	"native-kernel",
	"extra",
]
