# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-bundler"
publish = false
license.workspace = true
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
hyper.workspace = true
futures.workspace = true
hex.workspace = true
jsonrpsee-types.workspace = true
http-body-util.workspace = true
url.workspace = true
ethers.workspace = true

# Project
dsn-core.workspace = true
dsn-rpc.workspace = true
threshold-encryption.workspace = true
