#!/bin/sh

set -e

# shellcheck disable=SC1091
. /usr/share/debconf/confmodule

db_version 2.0
db_input high octez-dal-node/deprecation_notice || true
db_go || true

# work directory to store temporary files associated to this package
mkdir -p /var/run/octez-dal-node

# Reload systemd if unit files changed during upgrade
if [ -d /run/systemd/system ]; then
  systemctl daemon-reload || true
fi

#DEBHELPER#
