#!/bin/sh

set -eu

help() {
  cat << EOT
This script updates lock files in opam/virtual/.
These lock files contain the version number for our dependencies,
both direct and indirect. They do not include dev-only dependencies.

To produce this lock file, this scripts asks opam to use the commit:

  opam_repository_tag = $opam_repository_tag

from the public opam repository, to find a solution that is compatible
with opam/virtual/octez-deps.opam and opam/virtual/octez-dev-deps.opam.
Those two files are generated by the manifest
(see the documentation on profiles in manifest/manifest.mli).
Variable opam_repository_tag is defined in version.sh.
EOT
  exit 0
}

script_dir="$(cd "$(dirname "$0")" && echo "$(pwd -P)/")"
src_dir="$(dirname "$script_dir")"

# Needed for $opam_repository_tag
. scripts/version.sh

if [ "${1:-}" = "--help" ]; then
  help
fi

tmp_dir="$(mktemp -dt update_opam_lock.XXXXXXXX)"
tmp_opam_repo="$tmp_dir/repo"
tmp_opam_repo_name="update_opam_lock_tmp"
tmp_opam_switch="$tmp_dir/switch"

already_cleaned_up=no
clean_up() {
  if [ "$already_cleaned_up" = "no" ]; then
    already_cleaned_up=yes
    echo "---- Clean up."
    opam switch remove "$tmp_opam_switch" --yes || echo "Failed to remove switch."
    opam repository remove "$tmp_opam_repo_name" --all || echo "Failed to remove repository."
    rm -rf "$tmp_dir"
  fi
}

trap clean_up EXIT INT

# Ideally we would just set the opam repository URL to
# https://github.com/ocaml/opam-repository.git#$opam_repository_tag, but:
# - cloning the repo ourselves is actually significantly faster
#   (maybe opam does not know how to do a shallow clone);
# - this allows us to remove ocaml-system
#   (but we could also create the switch with --packages=ocaml-base-compiler.$ocaml_version);
# - this will allow us to remove other packages more easily in the future should we want to;
# - the --repositories argument of 'opam switch create' does not seem to understand
#   "url#tag", contrary to 'repository add'.
echo "---- Fetch opam repository commit: $opam_repository_tag"
git init "$tmp_opam_repo"
cd "$tmp_opam_repo"
git config --local protocol.version 2
git remote add origin https://github.com/ocaml/opam-repository
git fetch --depth 1 origin "$opam_repository_tag"
git checkout "$opam_repository_tag"
# Prevent opam from choosing the system-wide installed OCaml compiler.
rm -rf packages/ocaml-system
# Remove .git to be extra sure that opam will not use a different commit hash.
rm -rf .git
cd "$src_dir"

# We use --fake to tell opam not to actually compile the OCaml compiler.
# This breaks the switch but we will delete it afterwards anyway.
echo "---- Create a temporary fresh switch that uses our trimmed down repository."
unset OPAMSWITCH
opam switch create "$tmp_opam_switch" "$ocaml_version" \
  --repositories="$tmp_opam_repo_name"="$tmp_opam_repo" --no-install --fake
export OPAMSWITCH="$tmp_opam_switch"

# The default timeout (60 seconds) is often not enough.
export OPAMSOLVERTIMEOUT="${OPAMSOLVERTIMEOUT:-600}"

# Pin dream to 1.0.0~alpha8-octez and dream-httpaf to 1.0.0~alpha4-octez
echo "---- Pinning dream and dream-httpaf"
opam pin add dream-httpaf.1.0.0~alpha4-octez https://github.com/lthms/dream.git#c29c883a8a314bdb5dc90db865797e32cd4f5eee -n -y
opam pin add dream.1.0.0~alpha8-octez https://github.com/lthms/dream.git#c29c883a8a314bdb5dc90db865797e32cd4f5eee -n -y

# Pin cohttp to 5.3.1-octez
echo "---- Pinning cohttp"
opam pin add cohttp.5.3.1~octez https://github.com/killian-delarue/ocaml-cohttp.git#96ba1b08df549367bc67aef7dda535819181b3c8 -n -y
opam pin add cohttp-lwt.5.3.1~octez https://github.com/killian-delarue/ocaml-cohttp.git#96ba1b08df549367bc67aef7dda535819181b3c8 -n -y
opam pin add cohttp-lwt-unix.5.3.1~octez https://github.com/killian-delarue/ocaml-cohttp.git#96ba1b08df549367bc67aef7dda535819181b3c8 -n -y

# Pin base to a commit that's compatible with latest versions of Mac OS.
#
# Base has a mechanism to detect if `-mpopcnt` is compatible with `cc`, it works
# partially on recent versions of base. The version pinned is a fork of
# `v0.16.4` cherry-picking a work-in-progress pull request that improves the
# mechanism to check `-mpopcnt` compatibility.
echo "---- Pinning base"
opam pin add https://github.com/vch9/base.git#7f6581ba5e29fd340266cb901a59f24ebfbe67f1 -y

# Ask opam to find a solution that covers both:
# - 'octez-deps', so that we can compile Octez;
# - 'octez-dev-deps', so that the solution is compatible with tools that devs
#   may want to install.
# We use --fake to tell opam not to actually compile the packages.
echo "---- Run: 'opam install'"
opam install --yes --deps-only --fake opam/virtual/octez-deps.opam opam/virtual/octez-dev-deps.opam opam/virtual/release-tools-deps.opam --update-invariant

# The utop package is a special case.
# The pyml package, which is an actual dependency, optionally depends on utop.
# So if utop is installed, it is added in the lock file because of pyml.
# But utop is only a dev dependency, and as such does not need to appear in the lock file.
# So we remove it before generating the lock file.
echo "---- Run: 'opam remove utop'"
opam remove --yes --fake utop

echo "---- Run: 'opam lock'"
opam lock opam/virtual/octez-deps.opam
opam lock opam/virtual/release-tools-deps.opam

# Starting with `ocaml/opam-repository` commit hash
# 0b240d2960133fd3d8aa8f008d7aa79534caa3b9, ocaml-base-compiler now explicitly
# depends on system libraries.
# See https://github.com/ocaml/opam-repository/commit/0b240d2960133fd3d8aa8f008d7aa79534caa3b9
# Similarly, since we rely on eio_main, our dependencies tree contain system
# dependent libraries (e.g, on Linux, we use uring).
#
# Having these system-dependent libraries listed in our lock file make this
# lock file system-dependent as well. Fortunately, lock files are not close
# sets of dependencies we are allowed to use, but rather subsets of
# dependencies we are obligated to install. By dropping system-dependent
# dependencies from the lock file, we basically defer to Opam the choice to
# pick the most suited one, ensuring our lock file is portable.
ed -s octez-deps.opam.locked << EOF
g/host-arch-/d
g/host-system-/d
g/eio_linux/d
g/eio_posix/d
g/uring/d
w
EOF

mv octez-deps.opam.locked opam/virtual
echo "---- Updated: opam/virtual/octez-deps.opam.locked"

mv release-tools-deps.opam.locked opam/virtual
echo "---- Updated: opam/virtual/release-tools-deps.opam.locked"
