# SPDX-FileCopyrightText: 2025 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

UNIFFI_BINDINGS_DIR = uniffi_bindings

.PHONY: clean
clean:
	@rm -f $(UNIFFI_BINDINGS_DIR)/tezos.swift $(UNIFFI_BINDINGS_DIR)/tezosFFI.h $(UNIFFI_BINDINGS_DIR)/tezosFFI.modulemap
	@rm -f $(RESOURCES_DIR)/libtezos.so
