# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

.PHONY: all
all: check

.PHONY: build
build:
	@make -C inline_asm build

.PHONY: check
check:
	@make -C inline_asm check

.PHONY: clean
clean:
	@make -C inline_asm clean
