# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-sequencer"
publish = false
license.workspace = true
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
hyper.workspace = true
futures.workspace = true

# Project
dsn-core.workspace = true
dsn-rpc.workspace = true
